// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

/**
 * AVGRow is one free-form row in the "AVG check" table.
 */
export class AVGRow {
    /**
     * Creates a new AVGRow instance.
     * @param {Partial<AVGRow>} [$$source = {}] - The source object to create the AVGRow.
     */
    constructor($$source = {}) {
        if (!("onderwerp" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["onderwerp"] = "";
        }
        if (!("opmerking" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["opmerking"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AVGRow instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AVGRow}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AVGRow(/** @type {Partial<AVGRow>} */($$parsedSource));
    }
}

export class AWSProjectCfg {
    /**
     * Creates a new AWSProjectCfg instance.
     * @param {Partial<AWSProjectCfg>} [$$source = {}] - The source object to create the AWSProjectCfg.
     */
    constructor($$source = {}) {
        if (!("region" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["region"] = "";
        }
        if (!("service" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["service"] = "";
        }
        if (!("resourceId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["resourceId"] = "";
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("notes" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["notes"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AWSProjectCfg instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AWSProjectCfg}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AWSProjectCfg(/** @type {Partial<AWSProjectCfg>} */($$parsedSource));
    }
}

/**
 * ActieRow is one row in the "Acties en aandachtspunten" table.
 */
export class ActieRow {
    /**
     * Creates a new ActieRow instance.
     * @param {Partial<ActieRow>} [$$source = {}] - The source object to create the ActieRow.
     */
    constructor($$source = {}) {
        if (!("actie" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["actie"] = "";
        }
        if (!("wie" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["wie"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ActieRow instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ActieRow}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ActieRow(/** @type {Partial<ActieRow>} */($$parsedSource));
    }
}

/**
 * BasicAuth holds HTTP basic-auth credentials for one environment.
 * Pass is a keychain: reference, never a literal secret in git.
 */
export class BasicAuth {
    /**
     * Creates a new BasicAuth instance.
     * @param {Partial<BasicAuth>} [$$source = {}] - The source object to create the BasicAuth.
     */
    constructor($$source = {}) {
        if (!("user" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["user"] = "";
        }
        if (!("pass" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["pass"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BasicAuth instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BasicAuth}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BasicAuth(/** @type {Partial<BasicAuth>} */($$parsedSource));
    }
}

export class BlameLine {
    /**
     * Creates a new BlameLine instance.
     * @param {Partial<BlameLine>} [$$source = {}] - The source object to create the BlameLine.
     */
    constructor($$source = {}) {
        if (!("lineNo" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["lineNo"] = 0;
        }
        if (!("commit" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["commit"] = "";
        }
        if (!("author" in $$source)) {
            /**
             * @member
             * @type {Person}
             */
            this["author"] = (new Person());
        }
        if (!("date" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["date"] = null;
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BlameLine instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BlameLine}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("author" in $$parsedSource) {
            $$parsedSource["author"] = $$createField2_0($$parsedSource["author"]);
        }
        return new BlameLine(/** @type {Partial<BlameLine>} */($$parsedSource));
    }
}

export class Branch {
    /**
     * Creates a new Branch instance.
     * @param {Partial<Branch>} [$$source = {}] - The source object to create the Branch.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("fullRef" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["fullRef"] = "";
        }
        if (!("isRemote" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isRemote"] = false;
        }
        if (!("isCurrent" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isCurrent"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["upstream"] = undefined;
        }
        if (!("headCommit" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["headCommit"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Branch instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Branch}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Branch(/** @type {Partial<Branch>} */($$parsedSource));
    }
}

/**
 * @readonly
 * @enum {string}
 */
export const ChangeKind = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    ChangeAdded: "added",
    ChangeModified: "modified",
    ChangeDeleted: "deleted",
    ChangeRenamed: "renamed",
};

export class Commit {
    /**
     * Creates a new Commit instance.
     * @param {Partial<Commit>} [$$source = {}] - The source object to create the Commit.
     */
    constructor($$source = {}) {
        if (!("hash" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hash"] = "";
        }
        if (!("shortHash" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["shortHash"] = "";
        }
        if (!("author" in $$source)) {
            /**
             * @member
             * @type {Person}
             */
            this["author"] = (new Person());
        }
        if (!("committer" in $$source)) {
            /**
             * @member
             * @type {Person}
             */
            this["committer"] = (new Person());
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (!("subject" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["subject"] = "";
        }
        if (!("parents" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["parents"] = [];
        }
        if (!("refs" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["refs"] = [];
        }
        if (!("authoredAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["authoredAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Commit instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Commit}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType0;
        const $$createField3_0 = $$createType0;
        const $$createField6_0 = $$createType1;
        const $$createField7_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("author" in $$parsedSource) {
            $$parsedSource["author"] = $$createField2_0($$parsedSource["author"]);
        }
        if ("committer" in $$parsedSource) {
            $$parsedSource["committer"] = $$createField3_0($$parsedSource["committer"]);
        }
        if ("parents" in $$parsedSource) {
            $$parsedSource["parents"] = $$createField6_0($$parsedSource["parents"]);
        }
        if ("refs" in $$parsedSource) {
            $$parsedSource["refs"] = $$createField7_0($$parsedSource["refs"]);
        }
        return new Commit(/** @type {Partial<Commit>} */($$parsedSource));
    }
}

export class DeployConf {
    /**
     * Creates a new DeployConf instance.
     * @param {Partial<DeployConf>} [$$source = {}] - The source object to create the DeployConf.
     */
    constructor($$source = {}) {
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("link" in $$source)) {
            /**
             * @member
             * @type {DeployLinks}
             */
            this["link"] = (new DeployLinks());
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: string } | undefined}
             */
            this["vars"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeployConf instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DeployConf}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType2;
        const $$createField2_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("link" in $$parsedSource) {
            $$parsedSource["link"] = $$createField1_0($$parsedSource["link"]);
        }
        if ("vars" in $$parsedSource) {
            $$parsedSource["vars"] = $$createField2_0($$parsedSource["vars"]);
        }
        return new DeployConf(/** @type {Partial<DeployConf>} */($$parsedSource));
    }
}

export class DeployLinks {
    /**
     * Creates a new DeployLinks instance.
     * @param {Partial<DeployLinks>} [$$source = {}] - The source object to create the DeployLinks.
     */
    constructor($$source = {}) {
        if (!("test" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["test"] = "";
        }
        if (!("acc" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["acc"] = "";
        }
        if (!("prod" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["prod"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeployLinks instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DeployLinks}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DeployLinks(/** @type {Partial<DeployLinks>} */($$parsedSource));
    }
}

export class DiffHunk {
    /**
     * Creates a new DiffHunk instance.
     * @param {Partial<DiffHunk>} [$$source = {}] - The source object to create the DiffHunk.
     */
    constructor($$source = {}) {
        if (!("header" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["header"] = "";
        }
        if (!("oldStart" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["oldStart"] = 0;
        }
        if (!("oldLines" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["oldLines"] = 0;
        }
        if (!("newStart" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["newStart"] = 0;
        }
        if (!("newLines" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["newLines"] = 0;
        }
        if (!("lines" in $$source)) {
            /**
             * @member
             * @type {DiffLine[]}
             */
            this["lines"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DiffHunk instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DiffHunk}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("lines" in $$parsedSource) {
            $$parsedSource["lines"] = $$createField5_0($$parsedSource["lines"]);
        }
        return new DiffHunk(/** @type {Partial<DiffHunk>} */($$parsedSource));
    }
}

export class DiffLine {
    /**
     * Creates a new DiffLine instance.
     * @param {Partial<DiffLine>} [$$source = {}] - The source object to create the DiffLine.
     */
    constructor($$source = {}) {
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {DiffLineKind}
             */
            this["kind"] = DiffLineKind.$zero;
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["oldNum"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["newNum"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DiffLine instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DiffLine}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DiffLine(/** @type {Partial<DiffLine>} */($$parsedSource));
    }
}

/**
 * @readonly
 * @enum {string}
 */
export const DiffLineKind = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    LineContext: "context",
    LineAdd: "add",
    LineDel: "del",
};

/**
 * @readonly
 * @enum {string}
 */
export const DiffStatus = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    DiffUpToDate: "up_to_date",
    DiffUpdate: "update_available",
    DiffNotFound: "not_in_repo",
    DiffVulnerable: "vulnerable",
};

/**
 * EnvKey identifies one of the three comparable environments.
 * @readonly
 * @enum {string}
 */
export const EnvKey = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    EnvLocal: "local",
    EnvAcc: "acc",
    EnvProd: "prod",
};

export class FileChange {
    /**
     * Creates a new FileChange instance.
     * @param {Partial<FileChange>} [$$source = {}] - The source object to create the FileChange.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["oldPath"] = undefined;
        }
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {ChangeKind}
             */
            this["kind"] = ChangeKind.$zero;
        }
        if (!("insertions" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["insertions"] = 0;
        }
        if (!("deletions" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["deletions"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileChange instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FileChange}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileChange(/** @type {Partial<FileChange>} */($$parsedSource));
    }
}

export class FileDiff {
    /**
     * Creates a new FileDiff instance.
     * @param {Partial<FileDiff>} [$$source = {}] - The source object to create the FileDiff.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["oldPath"] = undefined;
        }
        if (!("binary" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["binary"] = false;
        }
        if (!("hunks" in $$source)) {
            /**
             * @member
             * @type {DiffHunk[]}
             */
            this["hunks"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileDiff instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FileDiff}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("hunks" in $$parsedSource) {
            $$parsedSource["hunks"] = $$createField3_0($$parsedSource["hunks"]);
        }
        return new FileDiff(/** @type {Partial<FileDiff>} */($$parsedSource));
    }
}

/**
 * Finding is one categorised visual difference for a step.
 */
export class Finding {
    /**
     * Creates a new Finding instance.
     * @param {Partial<Finding>} [$$source = {}] - The source object to create the Finding.
     */
    constructor($$source = {}) {
        if (!("category" in $$source)) {
            /**
             * @member
             * @type {FindingCategory}
             */
            this["category"] = FindingCategory.$zero;
        }
        if (!("severity" in $$source)) {
            /**
             * @member
             * @type {Severity}
             */
            this["severity"] = Severity.$zero;
        }
        if (!("where" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["where"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Finding instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Finding}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Finding(/** @type {Partial<Finding>} */($$parsedSource));
    }
}

/**
 * FindingCategory classifies a visual difference.
 * @readonly
 * @enum {string}
 */
export const FindingCategory = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    CatLayoutBreak: "layout-break",
    CatMissingElement: "missing-element",
    CatStyling: "styling",
    CatContentOnly: "content-only",
};

/**
 * Flow is a named happy-path scenario.
 */
export class Flow {
    /**
     * Creates a new Flow instance.
     * @param {Partial<Flow>} [$$source = {}] - The source object to create the Flow.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("steps" in $$source)) {
            /**
             * @member
             * @type {Step[]}
             */
            this["steps"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Flow instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Flow}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("steps" in $$parsedSource) {
            $$parsedSource["steps"] = $$createField1_0($$parsedSource["steps"]);
        }
        return new Flow(/** @type {Partial<Flow>} */($$parsedSource));
    }
}

export class GitStatus {
    /**
     * Creates a new GitStatus instance.
     * @param {Partial<GitStatus>} [$$source = {}] - The source object to create the GitStatus.
     */
    constructor($$source = {}) {
        if (!("branch" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["branch"] = "";
        }
        if (!("upstream" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["upstream"] = "";
        }
        if (!("ahead" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ahead"] = 0;
        }
        if (!("behind" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["behind"] = 0;
        }
        if (!("staged" in $$source)) {
            /**
             * @member
             * @type {FileChange[]}
             */
            this["staged"] = [];
        }
        if (!("unstaged" in $$source)) {
            /**
             * @member
             * @type {FileChange[]}
             */
            this["unstaged"] = [];
        }
        if (!("untracked" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["untracked"] = [];
        }
        if (!("conflicted" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["conflicted"] = [];
        }
        if (!("hasSubmodules" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["hasSubmodules"] = false;
        }
        if (!("isRepo" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isRepo"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GitStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GitStatus}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType11;
        const $$createField5_0 = $$createType11;
        const $$createField6_0 = $$createType1;
        const $$createField7_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("staged" in $$parsedSource) {
            $$parsedSource["staged"] = $$createField4_0($$parsedSource["staged"]);
        }
        if ("unstaged" in $$parsedSource) {
            $$parsedSource["unstaged"] = $$createField5_0($$parsedSource["unstaged"]);
        }
        if ("untracked" in $$parsedSource) {
            $$parsedSource["untracked"] = $$createField6_0($$parsedSource["untracked"]);
        }
        if ("conflicted" in $$parsedSource) {
            $$parsedSource["conflicted"] = $$createField7_0($$parsedSource["conflicted"]);
        }
        return new GitStatus(/** @type {Partial<GitStatus>} */($$parsedSource));
    }
}

export class GraphCommit {
    /**
     * Creates a new GraphCommit instance.
     * @param {Partial<GraphCommit>} [$$source = {}] - The source object to create the GraphCommit.
     */
    constructor($$source = {}) {
        if (!("hash" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hash"] = "";
        }
        if (!("shortHash" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["shortHash"] = "";
        }
        if (!("subject" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["subject"] = "";
        }
        if (!("author" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["author"] = "";
        }
        if (!("authorDate" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["authorDate"] = null;
        }
        if (!("parents" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["parents"] = [];
        }
        if (!("refs" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["refs"] = [];
        }
        if (!("lane" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["lane"] = 0;
        }
        if (!("columns" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["columns"] = 0;
        }
        if (!("edges" in $$source)) {
            /**
             * @member
             * @type {GraphEdge[]}
             */
            this["edges"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GraphCommit instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GraphCommit}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType1;
        const $$createField6_0 = $$createType1;
        const $$createField9_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("parents" in $$parsedSource) {
            $$parsedSource["parents"] = $$createField5_0($$parsedSource["parents"]);
        }
        if ("refs" in $$parsedSource) {
            $$parsedSource["refs"] = $$createField6_0($$parsedSource["refs"]);
        }
        if ("edges" in $$parsedSource) {
            $$parsedSource["edges"] = $$createField9_0($$parsedSource["edges"]);
        }
        return new GraphCommit(/** @type {Partial<GraphCommit>} */($$parsedSource));
    }
}

export class GraphEdge {
    /**
     * Creates a new GraphEdge instance.
     * @param {Partial<GraphEdge>} [$$source = {}] - The source object to create the GraphEdge.
     */
    constructor($$source = {}) {
        if (!("fromLane" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["fromLane"] = 0;
        }
        if (!("toLane" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["toLane"] = 0;
        }
        if (!("colorLane" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["colorLane"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GraphEdge instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GraphEdge}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GraphEdge(/** @type {Partial<GraphEdge>} */($$parsedSource));
    }
}

export class KinstaEnvBinding {
    /**
     * Creates a new KinstaEnvBinding instance.
     * @param {Partial<KinstaEnvBinding>} [$$source = {}] - The source object to create the KinstaEnvBinding.
     */
    constructor($$source = {}) {
        if (!("envId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["envId"] = "";
        }
        if (!("branch" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["branch"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new KinstaEnvBinding instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {KinstaEnvBinding}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new KinstaEnvBinding(/** @type {Partial<KinstaEnvBinding>} */($$parsedSource));
    }
}

export class KinstaProjectCfg {
    /**
     * Creates a new KinstaProjectCfg instance.
     * @param {Partial<KinstaProjectCfg>} [$$source = {}] - The source object to create the KinstaProjectCfg.
     */
    constructor($$source = {}) {
        if (!("siteId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["siteId"] = "";
        }
        if (!("environments" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: KinstaEnvBinding }}
             */
            this["environments"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new KinstaProjectCfg instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {KinstaProjectCfg}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType15;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("environments" in $$parsedSource) {
            $$parsedSource["environments"] = $$createField1_0($$parsedSource["environments"]);
        }
        return new KinstaProjectCfg(/** @type {Partial<KinstaProjectCfg>} */($$parsedSource));
    }
}

/**
 * ModelTier is a logical model choice; mapped to a concrete Anthropic model id
 * in the claude adapter (Plan 3).
 * @readonly
 * @enum {string}
 */
export const ModelTier = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    TierHaiku: "haiku",
    TierSonnet: "sonnet",
    TierOpus: "opus",
};

/**
 * MonitorRow is one row in the "Server, Uptime en TLS-monitoring" table.
 */
export class MonitorRow {
    /**
     * Creates a new MonitorRow instance.
     * @param {Partial<MonitorRow>} [$$source = {}] - The source object to create the MonitorRow.
     */
    constructor($$source = {}) {
        if (!("onderdeel" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["onderdeel"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("opmerking" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["opmerking"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MonitorRow instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MonitorRow}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MonitorRow(/** @type {Partial<MonitorRow>} */($$parsedSource));
    }
}

export class PaidPlugin {
    /**
     * Creates a new PaidPlugin instance.
     * @param {Partial<PaidPlugin>} [$$source = {}] - The source object to create the PaidPlugin.
     */
    constructor($$source = {}) {
        if (!("slug" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["slug"] = "";
        }
        if (!("displayName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["displayName"] = "";
        }
        if (!("latestVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["latestVersion"] = "";
        }
        if (!("zipPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["zipPath"] = "";
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["updatedAt"] = null;
        }
        if (!("downloadUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["downloadUrl"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PaidPlugin instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PaidPlugin}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PaidPlugin(/** @type {Partial<PaidPlugin>} */($$parsedSource));
    }
}

export class Person {
    /**
     * Creates a new Person instance.
     * @param {Partial<Person>} [$$source = {}] - The source object to create the Person.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("email" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["email"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Person instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Person}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Person(/** @type {Partial<Person>} */($$parsedSource));
    }
}

export class PluginDiff {
    /**
     * Creates a new PluginDiff instance.
     * @param {Partial<PluginDiff>} [$$source = {}] - The source object to create the PluginDiff.
     */
    constructor($$source = {}) {
        if (!("slug" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["slug"] = "";
        }
        if (!("installedVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["installedVersion"] = "";
        }
        if (!("availableVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["availableVersion"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {DiffStatus}
             */
            this["status"] = DiffStatus.$zero;
        }
        if (!("isVulnerable" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isVulnerable"] = false;
        }
        if (!("source" in $$source)) {
            /**
             * @member
             * @type {PluginSource}
             */
            this["source"] = PluginSource.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PluginDiff instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PluginDiff}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PluginDiff(/** @type {Partial<PluginDiff>} */($$parsedSource));
    }
}

/**
 * @readonly
 * @enum {string}
 */
export const PluginSource = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    SourcePrivateRepo: "private_repo",
    SourceWPOrg: "wp_org",
    SourceUnknown: "unknown",
};

export class Project {
    /**
     * Creates a new Project instance.
     * @param {Partial<Project>} [$$source = {}] - The source object to create the Project.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("displayName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["displayName"] = "";
        }
        if (!("provider" in $$source)) {
            /**
             * @member
             * @type {Provider}
             */
            this["provider"] = Provider.$zero;
        }
        if (!("config" in $$source)) {
            /**
             * @member
             * @type {ProjectConfig}
             */
            this["config"] = (new ProjectConfig());
        }
        if (!("deploy" in $$source)) {
            /**
             * @member
             * @type {DeployConf}
             */
            this["deploy"] = (new DeployConf());
        }
        if (!("git" in $$source)) {
            /**
             * @member
             * @type {GitStatus}
             */
            this["git"] = (new GitStatus());
        }
        if (!("lastScanAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["lastScanAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Project instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Project}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType16;
        const $$createField5_0 = $$createType17;
        const $$createField6_0 = $$createType18;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("config" in $$parsedSource) {
            $$parsedSource["config"] = $$createField4_0($$parsedSource["config"]);
        }
        if ("deploy" in $$parsedSource) {
            $$parsedSource["deploy"] = $$createField5_0($$parsedSource["deploy"]);
        }
        if ("git" in $$parsedSource) {
            $$parsedSource["git"] = $$createField6_0($$parsedSource["git"]);
        }
        return new Project(/** @type {Partial<Project>} */($$parsedSource));
    }
}

export class ProjectConfig {
    /**
     * Creates a new ProjectConfig instance.
     * @param {Partial<ProjectConfig>} [$$source = {}] - The source object to create the ProjectConfig.
     */
    constructor($$source = {}) {
        if (!("schemaVersion" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["schemaVersion"] = 0;
        }
        if (!("provider" in $$source)) {
            /**
             * @member
             * @type {Provider}
             */
            this["provider"] = Provider.$zero;
        }
        if (!("displayName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["displayName"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {KinstaProjectCfg | null | undefined}
             */
            this["kinsta"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {AWSProjectCfg | null | undefined}
             */
            this["aws"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {VPSProjectCfg | null | undefined}
             */
            this["vps"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {SSHTarget | null | undefined}
             */
            this["ssh"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {TestingCfg | null | undefined}
             */
            this["testing"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProjectConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProjectConfig}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType20;
        const $$createField4_0 = $$createType22;
        const $$createField5_0 = $$createType24;
        const $$createField6_0 = $$createType26;
        const $$createField7_0 = $$createType28;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("kinsta" in $$parsedSource) {
            $$parsedSource["kinsta"] = $$createField3_0($$parsedSource["kinsta"]);
        }
        if ("aws" in $$parsedSource) {
            $$parsedSource["aws"] = $$createField4_0($$parsedSource["aws"]);
        }
        if ("vps" in $$parsedSource) {
            $$parsedSource["vps"] = $$createField5_0($$parsedSource["vps"]);
        }
        if ("ssh" in $$parsedSource) {
            $$parsedSource["ssh"] = $$createField6_0($$parsedSource["ssh"]);
        }
        if ("testing" in $$parsedSource) {
            $$parsedSource["testing"] = $$createField7_0($$parsedSource["testing"]);
        }
        return new ProjectConfig(/** @type {Partial<ProjectConfig>} */($$parsedSource));
    }
}

export class ProjectStatusSummary {
    /**
     * Creates a new ProjectStatusSummary instance.
     * @param {Partial<ProjectStatusSummary>} [$$source = {}] - The source object to create the ProjectStatusSummary.
     */
    constructor($$source = {}) {
        if (!("projectId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["projectId"] = "";
        }
        if (!("displayName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["displayName"] = "";
        }
        if (!("branch" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["branch"] = "";
        }
        if (!("ahead" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ahead"] = 0;
        }
        if (!("behind" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["behind"] = 0;
        }
        if (!("dirty" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["dirty"] = false;
        }
        if (!("isRepo" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isRepo"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProjectStatusSummary instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProjectStatusSummary}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProjectStatusSummary(/** @type {Partial<ProjectStatusSummary>} */($$parsedSource));
    }
}

/**
 * @readonly
 * @enum {string}
 */
export const Provider = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    ProviderKinsta: "kinsta",
    ProviderAWS: "aws",
    ProviderVPS: "vps",
    ProviderNone: "none",
};

/**
 * Regression is something broken on the update side relative to the release
 * baseline, or a hard failure (5xx) that is always reported.
 */
export class Regression {
    /**
     * Creates a new Regression instance.
     * @param {Partial<Regression>} [$$source = {}] - The source object to create the Regression.
     */
    constructor($$source = {}) {
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {RegressionKind}
             */
            this["kind"] = RegressionKind.$zero;
        }
        if (!("detail" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["detail"] = "";
        }
        if (!("hard" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["hard"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Regression instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Regression}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Regression(/** @type {Partial<Regression>} */($$parsedSource));
    }
}

/**
 * RegressionKind distinguishes console vs HTTP-status regressions.
 * @readonly
 * @enum {string}
 */
export const RegressionKind = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    RegConsole: "console",
    RegStatus: "status",
};

/**
 * Report is a per-project, per-period client report ("Servicecontract
 * rapportage") mirroring the Bitfactory quarterly-report docx structure.
 */
export class Report {
    /**
     * Creates a new Report instance.
     * @param {Partial<Report>} [$$source = {}] - The source object to create the Report.
     */
    constructor($$source = {}) {
        if (!("projectId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["projectId"] = "";
        }
        if (!("period" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["period"] = "";
        }
        if (!("clientName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["clientName"] = "";
        }
        if (!("websiteName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["websiteName"] = "";
        }
        if (!("acties" in $$source)) {
            /**
             * @member
             * @type {ActieRow[]}
             */
            this["acties"] = [];
        }
        if (!("monitoring" in $$source)) {
            /**
             * @member
             * @type {MonitorRow[]}
             */
            this["monitoring"] = [];
        }
        if (!("software" in $$source)) {
            /**
             * @member
             * @type {SoftwareRow[]}
             */
            this["software"] = [];
        }
        if (!("dependencyUpdates" in $$source)) {
            /**
             * @member
             * @type {UpdateRow[]}
             */
            this["dependencyUpdates"] = [];
        }
        if (!("wpUpdates" in $$source)) {
            /**
             * @member
             * @type {UpdateRow[]}
             */
            this["wpUpdates"] = [];
        }
        if (!("avg" in $$source)) {
            /**
             * @member
             * @type {AVGRow[]}
             */
            this["avg"] = [];
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["updatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Report instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Report}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType30;
        const $$createField5_0 = $$createType32;
        const $$createField6_0 = $$createType34;
        const $$createField7_0 = $$createType36;
        const $$createField8_0 = $$createType36;
        const $$createField9_0 = $$createType38;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("acties" in $$parsedSource) {
            $$parsedSource["acties"] = $$createField4_0($$parsedSource["acties"]);
        }
        if ("monitoring" in $$parsedSource) {
            $$parsedSource["monitoring"] = $$createField5_0($$parsedSource["monitoring"]);
        }
        if ("software" in $$parsedSource) {
            $$parsedSource["software"] = $$createField6_0($$parsedSource["software"]);
        }
        if ("dependencyUpdates" in $$parsedSource) {
            $$parsedSource["dependencyUpdates"] = $$createField7_0($$parsedSource["dependencyUpdates"]);
        }
        if ("wpUpdates" in $$parsedSource) {
            $$parsedSource["wpUpdates"] = $$createField8_0($$parsedSource["wpUpdates"]);
        }
        if ("avg" in $$parsedSource) {
            $$parsedSource["avg"] = $$createField9_0($$parsedSource["avg"]);
        }
        return new Report(/** @type {Partial<Report>} */($$parsedSource));
    }
}

export class SSHTarget {
    /**
     * Creates a new SSHTarget instance.
     * @param {Partial<SSHTarget>} [$$source = {}] - The source object to create the SSHTarget.
     */
    constructor($$source = {}) {
        if (!("host" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["port"] = 0;
        }
        if (!("user" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["user"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["path"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SSHTarget instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SSHTarget}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SSHTarget(/** @type {Partial<SSHTarget>} */($$parsedSource));
    }
}

/**
 * Severity ranks a finding.
 * @readonly
 * @enum {string}
 */
export const Severity = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    /**
     * The Dutch values ("hoog"/"laag") are intentional user-facing report labels; do not translate to English.
     */
    SeverityHigh: "hoog",
    SeverityLow: "laag",
};

/**
 * SoftwareRow is one row in the "Server software & frameworks" table.
 */
export class SoftwareRow {
    /**
     * Creates a new SoftwareRow instance.
     * @param {Partial<SoftwareRow>} [$$source = {}] - The source object to create the SoftwareRow.
     */
    constructor($$source = {}) {
        if (!("component" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["component"] = "";
        }
        if (!("huidig" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["huidig"] = "";
        }
        if (!("ondersteundTot" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ondersteundTot"] = "";
        }
        if (!("laatste" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["laatste"] = "";
        }
        if (!("opmerking" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["opmerking"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SoftwareRow instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SoftwareRow}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SoftwareRow(/** @type {Partial<SoftwareRow>} */($$parsedSource));
    }
}

export class Stash {
    /**
     * Creates a new Stash instance.
     * @param {Partial<Stash>} [$$source = {}] - The source object to create the Stash.
     */
    constructor($$source = {}) {
        if (!("index" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["index"] = 0;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (!("branch" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["branch"] = "";
        }
        if (!("stashedAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["stashedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Stash instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Stash}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Stash(/** @type {Partial<Stash>} */($$parsedSource));
    }
}

/**
 * Step is one action in a flow. Target holds a natural-language description
 * (click/type/assert) or a path/URL (navigate). Selector is the last working
 * Playwright selector, cached so replay is deterministic; self-heal updates it.
 */
export class Step {
    /**
     * Creates a new Step instance.
     * @param {Partial<Step>} [$$source = {}] - The source object to create the Step.
     */
    constructor($$source = {}) {
        if (!("action" in $$source)) {
            /**
             * @member
             * @type {StepType}
             */
            this["action"] = StepType.$zero;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["target"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["value"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["selector"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Step instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Step}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Step(/** @type {Partial<Step>} */($$parsedSource));
    }
}

/**
 * StepResult is the compared outcome for a single step.
 */
export class StepResult {
    /**
     * Creates a new StepResult instance.
     * @param {Partial<StepResult>} [$$source = {}] - The source object to create the StepResult.
     */
    constructor($$source = {}) {
        if (!("index" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["index"] = 0;
        }
        if (!("action" in $$source)) {
            /**
             * @member
             * @type {StepType}
             */
            this["action"] = StepType.$zero;
        }
        if (!("screenshotBase" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["screenshotBase"] = "";
        }
        if (!("screenshotUpdate" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["screenshotUpdate"] = "";
        }
        if (!("findings" in $$source)) {
            /**
             * @member
             * @type {Finding[]}
             */
            this["findings"] = [];
        }
        if (!("regressions" in $$source)) {
            /**
             * @member
             * @type {Regression[]}
             */
            this["regressions"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["healNote"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StepResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {StepResult}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType40;
        const $$createField5_0 = $$createType42;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("findings" in $$parsedSource) {
            $$parsedSource["findings"] = $$createField4_0($$parsedSource["findings"]);
        }
        if ("regressions" in $$parsedSource) {
            $$parsedSource["regressions"] = $$createField5_0($$parsedSource["regressions"]);
        }
        return new StepResult(/** @type {Partial<StepResult>} */($$parsedSource));
    }
}

/**
 * StepType is the kind of action a flow step performs.
 * @readonly
 * @enum {string}
 */
export const StepType = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    StepNavigate: "navigate",
    StepClick: "click",
    StepInput: "type",
    StepLogin: "login",
    StepWait: "wait",
    StepAssert: "assert",
};

export class Tag {
    /**
     * Creates a new Tag instance.
     * @param {Partial<Tag>} [$$source = {}] - The source object to create the Tag.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("annotated" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["annotated"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["message"] = undefined;
        }
        if (!("commit" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["commit"] = "";
        }
        if (!("taggedAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["taggedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Tag instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Tag}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Tag(/** @type {Partial<Tag>} */($$parsedSource));
    }
}

/**
 * TestAccount is a site login used by `login` flow steps.
 * Pass is a keychain: reference.
 */
export class TestAccount {
    /**
     * Creates a new TestAccount instance.
     * @param {Partial<TestAccount>} [$$source = {}] - The source object to create the TestAccount.
     */
    constructor($$source = {}) {
        if (!("user" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["user"] = "";
        }
        if (!("pass" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["pass"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TestAccount instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TestAccount}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TestAccount(/** @type {Partial<TestAccount>} */($$parsedSource));
    }
}

/**
 * TestRun is one full comparison of a flow across two environments.
 */
export class TestRun {
    /**
     * Creates a new TestRun instance.
     * @param {Partial<TestRun>} [$$source = {}] - The source object to create the TestRun.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("projectId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["projectId"] = "";
        }
        if (!("flowName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["flowName"] = "";
        }
        if (!("baselineEnv" in $$source)) {
            /**
             * @member
             * @type {EnvKey}
             */
            this["baselineEnv"] = EnvKey.$zero;
        }
        if (!("updateEnv" in $$source)) {
            /**
             * @member
             * @type {EnvKey}
             */
            this["updateEnv"] = EnvKey.$zero;
        }
        if (!("models" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["models"] = [];
        }
        if (!("startedAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["startedAt"] = null;
        }
        if (!("steps" in $$source)) {
            /**
             * @member
             * @type {StepResult[]}
             */
            this["steps"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TestRun instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TestRun}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType1;
        const $$createField7_0 = $$createType44;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("models" in $$parsedSource) {
            $$parsedSource["models"] = $$createField5_0($$parsedSource["models"]);
        }
        if ("steps" in $$parsedSource) {
            $$parsedSource["steps"] = $$createField7_0($$parsedSource["steps"]);
        }
        return new TestRun(/** @type {Partial<TestRun>} */($$parsedSource));
    }
}

/**
 * TestingCfg lives under `testing:` in .rdm.yml (committed, no secrets).
 * acc/prod URLs still come from deploy_conf.json; only `local` is set here.
 */
export class TestingCfg {
    /**
     * Creates a new TestingCfg instance.
     * @param {Partial<TestingCfg>} [$$source = {}] - The source object to create the TestingCfg.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: string } | undefined}
             */
            this["environments"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: BasicAuth } | undefined}
             */
            this["basicAuth"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {TestAccount | null | undefined}
             */
            this["testAccount"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TestingCfg instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TestingCfg}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType3;
        const $$createField1_0 = $$createType46;
        const $$createField2_0 = $$createType48;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("environments" in $$parsedSource) {
            $$parsedSource["environments"] = $$createField0_0($$parsedSource["environments"]);
        }
        if ("basicAuth" in $$parsedSource) {
            $$parsedSource["basicAuth"] = $$createField1_0($$parsedSource["basicAuth"]);
        }
        if ("testAccount" in $$parsedSource) {
            $$parsedSource["testAccount"] = $$createField2_0($$parsedSource["testAccount"]);
        }
        return new TestingCfg(/** @type {Partial<TestingCfg>} */($$parsedSource));
    }
}

/**
 * UpdateRow is one row in the "Managed software-updates" tables (dependency
 * managers and WordPress core/plugins share the same shape).
 */
export class UpdateRow {
    /**
     * Creates a new UpdateRow instance.
     * @param {Partial<UpdateRow>} [$$source = {}] - The source object to create the UpdateRow.
     */
    constructor($$source = {}) {
        if (!("naam" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["naam"] = "";
        }
        if (!("uitgevoerd" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["uitgevoerd"] = "";
        }
        if (!("opmerking" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["opmerking"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateRow instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UpdateRow}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateRow(/** @type {Partial<UpdateRow>} */($$parsedSource));
    }
}

export class VPSProjectCfg {
    /**
     * Creates a new VPSProjectCfg instance.
     * @param {Partial<VPSProjectCfg>} [$$source = {}] - The source object to create the VPSProjectCfg.
     */
    constructor($$source = {}) {
        if (!("provider" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["provider"] = "";
        }
        if (!("ssh" in $$source)) {
            /**
             * @member
             * @type {SSHTarget}
             */
            this["ssh"] = (new SSHTarget());
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("notes" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["notes"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VPSProjectCfg instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {VPSProjectCfg}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType25;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("ssh" in $$parsedSource) {
            $$parsedSource["ssh"] = $$createField1_0($$parsedSource["ssh"]);
        }
        return new VPSProjectCfg(/** @type {Partial<VPSProjectCfg>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = Person.createFrom;
const $$createType1 = $Create.Array($Create.Any);
const $$createType2 = DeployLinks.createFrom;
const $$createType3 = $Create.Map($Create.Any, $Create.Any);
const $$createType4 = DiffLine.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = DiffHunk.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = Step.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = FileChange.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = GraphEdge.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = KinstaEnvBinding.createFrom;
const $$createType15 = $Create.Map($Create.Any, $$createType14);
const $$createType16 = ProjectConfig.createFrom;
const $$createType17 = DeployConf.createFrom;
const $$createType18 = GitStatus.createFrom;
const $$createType19 = KinstaProjectCfg.createFrom;
const $$createType20 = $Create.Nullable($$createType19);
const $$createType21 = AWSProjectCfg.createFrom;
const $$createType22 = $Create.Nullable($$createType21);
const $$createType23 = VPSProjectCfg.createFrom;
const $$createType24 = $Create.Nullable($$createType23);
const $$createType25 = SSHTarget.createFrom;
const $$createType26 = $Create.Nullable($$createType25);
const $$createType27 = TestingCfg.createFrom;
const $$createType28 = $Create.Nullable($$createType27);
const $$createType29 = ActieRow.createFrom;
const $$createType30 = $Create.Array($$createType29);
const $$createType31 = MonitorRow.createFrom;
const $$createType32 = $Create.Array($$createType31);
const $$createType33 = SoftwareRow.createFrom;
const $$createType34 = $Create.Array($$createType33);
const $$createType35 = UpdateRow.createFrom;
const $$createType36 = $Create.Array($$createType35);
const $$createType37 = AVGRow.createFrom;
const $$createType38 = $Create.Array($$createType37);
const $$createType39 = Finding.createFrom;
const $$createType40 = $Create.Array($$createType39);
const $$createType41 = Regression.createFrom;
const $$createType42 = $Create.Array($$createType41);
const $$createType43 = StepResult.createFrom;
const $$createType44 = $Create.Array($$createType43);
const $$createType45 = BasicAuth.createFrom;
const $$createType46 = $Create.Map($Create.Any, $$createType45);
const $$createType47 = TestAccount.createFrom;
const $$createType48 = $Create.Nullable($$createType47);
