// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

export class AWSProjectCfg {
    "region": string;
    "service": string;
    "resourceId": string;
    "url": string;
    "notes": string;

    /** Creates a new AWSProjectCfg instance. */
    constructor($$source: Partial<AWSProjectCfg> = {}) {
        if (!("region" in $$source)) {
            this["region"] = "";
        }
        if (!("service" in $$source)) {
            this["service"] = "";
        }
        if (!("resourceId" in $$source)) {
            this["resourceId"] = "";
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("notes" in $$source)) {
            this["notes"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AWSProjectCfg instance from a string or object.
     */
    static createFrom($$source: any = {}): AWSProjectCfg {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AWSProjectCfg($$parsedSource as Partial<AWSProjectCfg>);
    }
}

export class BlameLine {
    "lineNo": number;
    "commit": string;
    "author": Person;
    "date": time$0.Time;
    "content": string;

    /** Creates a new BlameLine instance. */
    constructor($$source: Partial<BlameLine> = {}) {
        if (!("lineNo" in $$source)) {
            this["lineNo"] = 0;
        }
        if (!("commit" in $$source)) {
            this["commit"] = "";
        }
        if (!("author" in $$source)) {
            this["author"] = (new Person());
        }
        if (!("date" in $$source)) {
            this["date"] = null;
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BlameLine instance from a string or object.
     */
    static createFrom($$source: any = {}): BlameLine {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("author" in $$parsedSource) {
            $$parsedSource["author"] = $$createField2_0($$parsedSource["author"]);
        }
        return new BlameLine($$parsedSource as Partial<BlameLine>);
    }
}

export class Branch {
    "name": string;
    "fullRef": string;
    "isRemote": boolean;
    "isCurrent": boolean;
    "upstream"?: string;
    "headCommit": string;

    /** Creates a new Branch instance. */
    constructor($$source: Partial<Branch> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("fullRef" in $$source)) {
            this["fullRef"] = "";
        }
        if (!("isRemote" in $$source)) {
            this["isRemote"] = false;
        }
        if (!("isCurrent" in $$source)) {
            this["isCurrent"] = false;
        }
        if (!("headCommit" in $$source)) {
            this["headCommit"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Branch instance from a string or object.
     */
    static createFrom($$source: any = {}): Branch {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Branch($$parsedSource as Partial<Branch>);
    }
}

export enum ChangeKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ChangeAdded = "added",
    ChangeModified = "modified",
    ChangeDeleted = "deleted",
    ChangeRenamed = "renamed",
};

export class Commit {
    "hash": string;
    "shortHash": string;
    "author": Person;
    "committer": Person;
    "message": string;
    "subject": string;
    "parents": string[];
    "refs": string[];
    "authoredAt": time$0.Time;

    /** Creates a new Commit instance. */
    constructor($$source: Partial<Commit> = {}) {
        if (!("hash" in $$source)) {
            this["hash"] = "";
        }
        if (!("shortHash" in $$source)) {
            this["shortHash"] = "";
        }
        if (!("author" in $$source)) {
            this["author"] = (new Person());
        }
        if (!("committer" in $$source)) {
            this["committer"] = (new Person());
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("subject" in $$source)) {
            this["subject"] = "";
        }
        if (!("parents" in $$source)) {
            this["parents"] = [];
        }
        if (!("refs" in $$source)) {
            this["refs"] = [];
        }
        if (!("authoredAt" in $$source)) {
            this["authoredAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Commit instance from a string or object.
     */
    static createFrom($$source: any = {}): Commit {
        const $$createField2_0 = $$createType0;
        const $$createField3_0 = $$createType0;
        const $$createField6_0 = $$createType1;
        const $$createField7_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("author" in $$parsedSource) {
            $$parsedSource["author"] = $$createField2_0($$parsedSource["author"]);
        }
        if ("committer" in $$parsedSource) {
            $$parsedSource["committer"] = $$createField3_0($$parsedSource["committer"]);
        }
        if ("parents" in $$parsedSource) {
            $$parsedSource["parents"] = $$createField6_0($$parsedSource["parents"]);
        }
        if ("refs" in $$parsedSource) {
            $$parsedSource["refs"] = $$createField7_0($$parsedSource["refs"]);
        }
        return new Commit($$parsedSource as Partial<Commit>);
    }
}

export class DeployConf {
    "type": string;
    "link": DeployLinks;
    "vars"?: { [_ in string]?: string };

    /** Creates a new DeployConf instance. */
    constructor($$source: Partial<DeployConf> = {}) {
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("link" in $$source)) {
            this["link"] = (new DeployLinks());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeployConf instance from a string or object.
     */
    static createFrom($$source: any = {}): DeployConf {
        const $$createField1_0 = $$createType2;
        const $$createField2_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("link" in $$parsedSource) {
            $$parsedSource["link"] = $$createField1_0($$parsedSource["link"]);
        }
        if ("vars" in $$parsedSource) {
            $$parsedSource["vars"] = $$createField2_0($$parsedSource["vars"]);
        }
        return new DeployConf($$parsedSource as Partial<DeployConf>);
    }
}

export class DeployLinks {
    "test": string;
    "acc": string;
    "prod": string;

    /** Creates a new DeployLinks instance. */
    constructor($$source: Partial<DeployLinks> = {}) {
        if (!("test" in $$source)) {
            this["test"] = "";
        }
        if (!("acc" in $$source)) {
            this["acc"] = "";
        }
        if (!("prod" in $$source)) {
            this["prod"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeployLinks instance from a string or object.
     */
    static createFrom($$source: any = {}): DeployLinks {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DeployLinks($$parsedSource as Partial<DeployLinks>);
    }
}

export class DiffHunk {
    "header": string;
    "oldStart": number;
    "oldLines": number;
    "newStart": number;
    "newLines": number;
    "lines": DiffLine[];

    /** Creates a new DiffHunk instance. */
    constructor($$source: Partial<DiffHunk> = {}) {
        if (!("header" in $$source)) {
            this["header"] = "";
        }
        if (!("oldStart" in $$source)) {
            this["oldStart"] = 0;
        }
        if (!("oldLines" in $$source)) {
            this["oldLines"] = 0;
        }
        if (!("newStart" in $$source)) {
            this["newStart"] = 0;
        }
        if (!("newLines" in $$source)) {
            this["newLines"] = 0;
        }
        if (!("lines" in $$source)) {
            this["lines"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DiffHunk instance from a string or object.
     */
    static createFrom($$source: any = {}): DiffHunk {
        const $$createField5_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("lines" in $$parsedSource) {
            $$parsedSource["lines"] = $$createField5_0($$parsedSource["lines"]);
        }
        return new DiffHunk($$parsedSource as Partial<DiffHunk>);
    }
}

export class DiffLine {
    "kind": DiffLineKind;
    "content": string;
    "oldNum"?: number;
    "newNum"?: number;

    /** Creates a new DiffLine instance. */
    constructor($$source: Partial<DiffLine> = {}) {
        if (!("kind" in $$source)) {
            this["kind"] = DiffLineKind.$zero;
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DiffLine instance from a string or object.
     */
    static createFrom($$source: any = {}): DiffLine {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DiffLine($$parsedSource as Partial<DiffLine>);
    }
}

export enum DiffLineKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    LineContext = "context",
    LineAdd = "add",
    LineDel = "del",
};

export class FileChange {
    "path": string;
    "oldPath"?: string;
    "kind": ChangeKind;
    "insertions": number;
    "deletions": number;

    /** Creates a new FileChange instance. */
    constructor($$source: Partial<FileChange> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = ChangeKind.$zero;
        }
        if (!("insertions" in $$source)) {
            this["insertions"] = 0;
        }
        if (!("deletions" in $$source)) {
            this["deletions"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileChange instance from a string or object.
     */
    static createFrom($$source: any = {}): FileChange {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileChange($$parsedSource as Partial<FileChange>);
    }
}

export class FileDiff {
    "path": string;
    "oldPath"?: string;
    "binary": boolean;
    "hunks": DiffHunk[];

    /** Creates a new FileDiff instance. */
    constructor($$source: Partial<FileDiff> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("binary" in $$source)) {
            this["binary"] = false;
        }
        if (!("hunks" in $$source)) {
            this["hunks"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileDiff instance from a string or object.
     */
    static createFrom($$source: any = {}): FileDiff {
        const $$createField3_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("hunks" in $$parsedSource) {
            $$parsedSource["hunks"] = $$createField3_0($$parsedSource["hunks"]);
        }
        return new FileDiff($$parsedSource as Partial<FileDiff>);
    }
}

export class GitStatus {
    "branch": string;
    "upstream": string;
    "ahead": number;
    "behind": number;
    "staged": FileChange[];
    "unstaged": FileChange[];
    "untracked": string[];
    "conflicted": string[];
    "hasSubmodules": boolean;
    "isRepo": boolean;

    /** Creates a new GitStatus instance. */
    constructor($$source: Partial<GitStatus> = {}) {
        if (!("branch" in $$source)) {
            this["branch"] = "";
        }
        if (!("upstream" in $$source)) {
            this["upstream"] = "";
        }
        if (!("ahead" in $$source)) {
            this["ahead"] = 0;
        }
        if (!("behind" in $$source)) {
            this["behind"] = 0;
        }
        if (!("staged" in $$source)) {
            this["staged"] = [];
        }
        if (!("unstaged" in $$source)) {
            this["unstaged"] = [];
        }
        if (!("untracked" in $$source)) {
            this["untracked"] = [];
        }
        if (!("conflicted" in $$source)) {
            this["conflicted"] = [];
        }
        if (!("hasSubmodules" in $$source)) {
            this["hasSubmodules"] = false;
        }
        if (!("isRepo" in $$source)) {
            this["isRepo"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GitStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): GitStatus {
        const $$createField4_0 = $$createType9;
        const $$createField5_0 = $$createType9;
        const $$createField6_0 = $$createType1;
        const $$createField7_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("staged" in $$parsedSource) {
            $$parsedSource["staged"] = $$createField4_0($$parsedSource["staged"]);
        }
        if ("unstaged" in $$parsedSource) {
            $$parsedSource["unstaged"] = $$createField5_0($$parsedSource["unstaged"]);
        }
        if ("untracked" in $$parsedSource) {
            $$parsedSource["untracked"] = $$createField6_0($$parsedSource["untracked"]);
        }
        if ("conflicted" in $$parsedSource) {
            $$parsedSource["conflicted"] = $$createField7_0($$parsedSource["conflicted"]);
        }
        return new GitStatus($$parsedSource as Partial<GitStatus>);
    }
}

export class GraphCommit {
    "hash": string;
    "shortHash": string;
    "subject": string;
    "author": string;
    "authorDate": time$0.Time;
    "parents": string[];
    "refs": string[];
    "lane": number;
    "columns": number;
    "edges": GraphEdge[];

    /** Creates a new GraphCommit instance. */
    constructor($$source: Partial<GraphCommit> = {}) {
        if (!("hash" in $$source)) {
            this["hash"] = "";
        }
        if (!("shortHash" in $$source)) {
            this["shortHash"] = "";
        }
        if (!("subject" in $$source)) {
            this["subject"] = "";
        }
        if (!("author" in $$source)) {
            this["author"] = "";
        }
        if (!("authorDate" in $$source)) {
            this["authorDate"] = null;
        }
        if (!("parents" in $$source)) {
            this["parents"] = [];
        }
        if (!("refs" in $$source)) {
            this["refs"] = [];
        }
        if (!("lane" in $$source)) {
            this["lane"] = 0;
        }
        if (!("columns" in $$source)) {
            this["columns"] = 0;
        }
        if (!("edges" in $$source)) {
            this["edges"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GraphCommit instance from a string or object.
     */
    static createFrom($$source: any = {}): GraphCommit {
        const $$createField5_0 = $$createType1;
        const $$createField6_0 = $$createType1;
        const $$createField9_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("parents" in $$parsedSource) {
            $$parsedSource["parents"] = $$createField5_0($$parsedSource["parents"]);
        }
        if ("refs" in $$parsedSource) {
            $$parsedSource["refs"] = $$createField6_0($$parsedSource["refs"]);
        }
        if ("edges" in $$parsedSource) {
            $$parsedSource["edges"] = $$createField9_0($$parsedSource["edges"]);
        }
        return new GraphCommit($$parsedSource as Partial<GraphCommit>);
    }
}

export class GraphEdge {
    "fromLane": number;
    "toLane": number;
    "colorLane": number;

    /** Creates a new GraphEdge instance. */
    constructor($$source: Partial<GraphEdge> = {}) {
        if (!("fromLane" in $$source)) {
            this["fromLane"] = 0;
        }
        if (!("toLane" in $$source)) {
            this["toLane"] = 0;
        }
        if (!("colorLane" in $$source)) {
            this["colorLane"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GraphEdge instance from a string or object.
     */
    static createFrom($$source: any = {}): GraphEdge {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GraphEdge($$parsedSource as Partial<GraphEdge>);
    }
}

export class KinstaEnvBinding {
    "envId": string;
    "branch": string;

    /** Creates a new KinstaEnvBinding instance. */
    constructor($$source: Partial<KinstaEnvBinding> = {}) {
        if (!("envId" in $$source)) {
            this["envId"] = "";
        }
        if (!("branch" in $$source)) {
            this["branch"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new KinstaEnvBinding instance from a string or object.
     */
    static createFrom($$source: any = {}): KinstaEnvBinding {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new KinstaEnvBinding($$parsedSource as Partial<KinstaEnvBinding>);
    }
}

export class KinstaProjectCfg {
    "siteId": string;
    "environments": { [_ in string]?: KinstaEnvBinding };

    /** Creates a new KinstaProjectCfg instance. */
    constructor($$source: Partial<KinstaProjectCfg> = {}) {
        if (!("siteId" in $$source)) {
            this["siteId"] = "";
        }
        if (!("environments" in $$source)) {
            this["environments"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new KinstaProjectCfg instance from a string or object.
     */
    static createFrom($$source: any = {}): KinstaProjectCfg {
        const $$createField1_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("environments" in $$parsedSource) {
            $$parsedSource["environments"] = $$createField1_0($$parsedSource["environments"]);
        }
        return new KinstaProjectCfg($$parsedSource as Partial<KinstaProjectCfg>);
    }
}

export class Person {
    "name": string;
    "email": string;

    /** Creates a new Person instance. */
    constructor($$source: Partial<Person> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("email" in $$source)) {
            this["email"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Person instance from a string or object.
     */
    static createFrom($$source: any = {}): Person {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Person($$parsedSource as Partial<Person>);
    }
}

export class Project {
    "id": string;
    "path": string;
    "displayName": string;
    "provider": Provider;
    "config": ProjectConfig;
    "deploy": DeployConf;
    "git": GitStatus;
    "lastScanAt": time$0.Time;

    /** Creates a new Project instance. */
    constructor($$source: Partial<Project> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("displayName" in $$source)) {
            this["displayName"] = "";
        }
        if (!("provider" in $$source)) {
            this["provider"] = Provider.$zero;
        }
        if (!("config" in $$source)) {
            this["config"] = (new ProjectConfig());
        }
        if (!("deploy" in $$source)) {
            this["deploy"] = (new DeployConf());
        }
        if (!("git" in $$source)) {
            this["git"] = (new GitStatus());
        }
        if (!("lastScanAt" in $$source)) {
            this["lastScanAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Project instance from a string or object.
     */
    static createFrom($$source: any = {}): Project {
        const $$createField4_0 = $$createType14;
        const $$createField5_0 = $$createType15;
        const $$createField6_0 = $$createType16;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("config" in $$parsedSource) {
            $$parsedSource["config"] = $$createField4_0($$parsedSource["config"]);
        }
        if ("deploy" in $$parsedSource) {
            $$parsedSource["deploy"] = $$createField5_0($$parsedSource["deploy"]);
        }
        if ("git" in $$parsedSource) {
            $$parsedSource["git"] = $$createField6_0($$parsedSource["git"]);
        }
        return new Project($$parsedSource as Partial<Project>);
    }
}

export class ProjectConfig {
    "schemaVersion": number;
    "provider": Provider;
    "displayName": string;
    "kinsta"?: KinstaProjectCfg | null;
    "aws"?: AWSProjectCfg | null;
    "vps"?: VPSProjectCfg | null;
    "ssh"?: SSHTarget | null;

    /** Creates a new ProjectConfig instance. */
    constructor($$source: Partial<ProjectConfig> = {}) {
        if (!("schemaVersion" in $$source)) {
            this["schemaVersion"] = 0;
        }
        if (!("provider" in $$source)) {
            this["provider"] = Provider.$zero;
        }
        if (!("displayName" in $$source)) {
            this["displayName"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProjectConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): ProjectConfig {
        const $$createField3_0 = $$createType18;
        const $$createField4_0 = $$createType20;
        const $$createField5_0 = $$createType22;
        const $$createField6_0 = $$createType24;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("kinsta" in $$parsedSource) {
            $$parsedSource["kinsta"] = $$createField3_0($$parsedSource["kinsta"]);
        }
        if ("aws" in $$parsedSource) {
            $$parsedSource["aws"] = $$createField4_0($$parsedSource["aws"]);
        }
        if ("vps" in $$parsedSource) {
            $$parsedSource["vps"] = $$createField5_0($$parsedSource["vps"]);
        }
        if ("ssh" in $$parsedSource) {
            $$parsedSource["ssh"] = $$createField6_0($$parsedSource["ssh"]);
        }
        return new ProjectConfig($$parsedSource as Partial<ProjectConfig>);
    }
}

export class ProjectStatusSummary {
    "projectId": string;
    "displayName": string;
    "branch": string;
    "ahead": number;
    "behind": number;
    "dirty": boolean;
    "isRepo": boolean;

    /** Creates a new ProjectStatusSummary instance. */
    constructor($$source: Partial<ProjectStatusSummary> = {}) {
        if (!("projectId" in $$source)) {
            this["projectId"] = "";
        }
        if (!("displayName" in $$source)) {
            this["displayName"] = "";
        }
        if (!("branch" in $$source)) {
            this["branch"] = "";
        }
        if (!("ahead" in $$source)) {
            this["ahead"] = 0;
        }
        if (!("behind" in $$source)) {
            this["behind"] = 0;
        }
        if (!("dirty" in $$source)) {
            this["dirty"] = false;
        }
        if (!("isRepo" in $$source)) {
            this["isRepo"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProjectStatusSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): ProjectStatusSummary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProjectStatusSummary($$parsedSource as Partial<ProjectStatusSummary>);
    }
}

export enum Provider {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ProviderKinsta = "kinsta",
    ProviderAWS = "aws",
    ProviderVPS = "vps",
    ProviderNone = "none",
};

export class SSHTarget {
    "host": string;
    "port": number;
    "user": string;
    "path"?: string;

    /** Creates a new SSHTarget instance. */
    constructor($$source: Partial<SSHTarget> = {}) {
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("user" in $$source)) {
            this["user"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SSHTarget instance from a string or object.
     */
    static createFrom($$source: any = {}): SSHTarget {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SSHTarget($$parsedSource as Partial<SSHTarget>);
    }
}

export class Stash {
    "index": number;
    "message": string;
    "branch": string;
    "stashedAt": time$0.Time;

    /** Creates a new Stash instance. */
    constructor($$source: Partial<Stash> = {}) {
        if (!("index" in $$source)) {
            this["index"] = 0;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("branch" in $$source)) {
            this["branch"] = "";
        }
        if (!("stashedAt" in $$source)) {
            this["stashedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Stash instance from a string or object.
     */
    static createFrom($$source: any = {}): Stash {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Stash($$parsedSource as Partial<Stash>);
    }
}

export class Tag {
    "name": string;
    "annotated": boolean;
    "message"?: string;
    "commit": string;
    "taggedAt": time$0.Time;

    /** Creates a new Tag instance. */
    constructor($$source: Partial<Tag> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("annotated" in $$source)) {
            this["annotated"] = false;
        }
        if (!("commit" in $$source)) {
            this["commit"] = "";
        }
        if (!("taggedAt" in $$source)) {
            this["taggedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Tag instance from a string or object.
     */
    static createFrom($$source: any = {}): Tag {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Tag($$parsedSource as Partial<Tag>);
    }
}

export class VPSProjectCfg {
    "provider": string;
    "ssh": SSHTarget;
    "url": string;
    "notes": string;

    /** Creates a new VPSProjectCfg instance. */
    constructor($$source: Partial<VPSProjectCfg> = {}) {
        if (!("provider" in $$source)) {
            this["provider"] = "";
        }
        if (!("ssh" in $$source)) {
            this["ssh"] = (new SSHTarget());
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("notes" in $$source)) {
            this["notes"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VPSProjectCfg instance from a string or object.
     */
    static createFrom($$source: any = {}): VPSProjectCfg {
        const $$createField1_0 = $$createType23;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("ssh" in $$parsedSource) {
            $$parsedSource["ssh"] = $$createField1_0($$parsedSource["ssh"]);
        }
        return new VPSProjectCfg($$parsedSource as Partial<VPSProjectCfg>);
    }
}

// Private type creation functions
const $$createType0 = Person.createFrom;
const $$createType1 = $Create.Array($Create.Any);
const $$createType2 = DeployLinks.createFrom;
const $$createType3 = $Create.Map($Create.Any, $Create.Any);
const $$createType4 = DiffLine.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = DiffHunk.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = FileChange.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = GraphEdge.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = KinstaEnvBinding.createFrom;
const $$createType13 = $Create.Map($Create.Any, $$createType12);
const $$createType14 = ProjectConfig.createFrom;
const $$createType15 = DeployConf.createFrom;
const $$createType16 = GitStatus.createFrom;
const $$createType17 = KinstaProjectCfg.createFrom;
const $$createType18 = $Create.Nullable($$createType17);
const $$createType19 = AWSProjectCfg.createFrom;
const $$createType20 = $Create.Nullable($$createType19);
const $$createType21 = VPSProjectCfg.createFrom;
const $$createType22 = $Create.Nullable($$createType21);
const $$createType23 = SSHTarget.createFrom;
const $$createType24 = $Create.Nullable($$createType23);
