// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ContainerInfo holds runtime version info for an environment.
 */
export class ContainerInfo {
    /**
     * Creates a new ContainerInfo instance.
     * @param {Partial<ContainerInfo>} [$$source = {}] - The source object to create the ContainerInfo.
     */
    constructor($$source = {}) {
        if (!("php_engine_version" in $$source)) {
            /**
             * e.g. "php8.3"
             * @member
             * @type {string}
             */
            this["php_engine_version"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ContainerInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ContainerInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ContainerInfo(/** @type {Partial<ContainerInfo>} */($$parsedSource));
    }
}

/**
 * Environment represents a full Kinsta site environment (from /sites/{id}/environments).
 */
export class Environment {
    /**
     * Creates a new Environment instance.
     * @param {Partial<Environment>} [$$source = {}] - The source object to create the Environment.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("display_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["display_name"] = "";
        }
        if (!("is_blocked" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["is_blocked"] = false;
        }
        if (!("wordpress_version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["wordpress_version"] = "";
        }
        if (!("container_info" in $$source)) {
            /**
             * @member
             * @type {ContainerInfo}
             */
            this["container_info"] = (new ContainerInfo());
        }
        if (!("ssh_connection" in $$source)) {
            /**
             * @member
             * @type {SSHConnection}
             */
            this["ssh_connection"] = (new SSHConnection());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Environment instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Environment}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType0;
        const $$createField6_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("container_info" in $$parsedSource) {
            $$parsedSource["container_info"] = $$createField5_0($$parsedSource["container_info"]);
        }
        if ("ssh_connection" in $$parsedSource) {
            $$parsedSource["ssh_connection"] = $$createField6_0($$parsedSource["ssh_connection"]);
        }
        return new Environment(/** @type {Partial<Environment>} */($$parsedSource));
    }
}

/**
 * EnvironmentDetails holds plugins + themes for an environment.
 */
export class EnvironmentDetails {
    /**
     * Creates a new EnvironmentDetails instance.
     * @param {Partial<EnvironmentDetails>} [$$source = {}] - The source object to create the EnvironmentDetails.
     */
    constructor($$source = {}) {
        if (!("plugins" in $$source)) {
            /**
             * @member
             * @type {Plugin[]}
             */
            this["plugins"] = [];
        }
        if (!("themes" in $$source)) {
            /**
             * @member
             * @type {Theme[]}
             */
            this["themes"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EnvironmentDetails instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {EnvironmentDetails}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType3;
        const $$createField1_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("plugins" in $$parsedSource) {
            $$parsedSource["plugins"] = $$createField0_0($$parsedSource["plugins"]);
        }
        if ("themes" in $$parsedSource) {
            $$parsedSource["themes"] = $$createField1_0($$parsedSource["themes"]);
        }
        return new EnvironmentDetails(/** @type {Partial<EnvironmentDetails>} */($$parsedSource));
    }
}

/**
 * Plugin represents a WordPress plugin (from /wp-plugins).
 */
export class Plugin {
    /**
     * Creates a new Plugin instance.
     * @param {Partial<Plugin>} [$$source = {}] - The source object to create the Plugin.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * "active" | "inactive"
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("update" in $$source)) {
            /**
             * "available" or ""
             * @member
             * @type {string}
             */
            this["update"] = "";
        }
        if (!("update_version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["update_version"] = "";
        }
        if (!("is_version_vulnerable" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["is_version_vulnerable"] = false;
        }
        if (!("is_update_version_vulnerable" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["is_update_version_vulnerable"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Plugin instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Plugin}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Plugin(/** @type {Partial<Plugin>} */($$parsedSource));
    }
}

/**
 * SSHConnection holds SSH access details.
 */
export class SSHConnection {
    /**
     * Creates a new SSHConnection instance.
     * @param {Partial<SSHConnection>} [$$source = {}] - The source object to create the SSHConnection.
     */
    constructor($$source = {}) {
        if (!("ssh_port" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ssh_port"] = "";
        }
        if (!("ssh_ip" in $$source)) {
            /**
             * @member
             * @type {{"external_ip": string}}
             */
            this["ssh_ip"] = {"external_ip": ""};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SSHConnection instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SSHConnection}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SSHConnection(/** @type {Partial<SSHConnection>} */($$parsedSource));
    }
}

/**
 * Site represents a Kinsta site.
 */
export class Site {
    /**
     * Creates a new Site instance.
     * @param {Partial<Site>} [$$source = {}] - The source object to create the Site.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("display_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["display_name"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Site instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Site}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Site(/** @type {Partial<Site>} */($$parsedSource));
    }
}

/**
 * SiteDetails wraps site + its environments (with full details).
 */
export class SiteDetails {
    /**
     * Creates a new SiteDetails instance.
     * @param {Partial<SiteDetails>} [$$source = {}] - The source object to create the SiteDetails.
     */
    constructor($$source = {}) {
        if (!("site" in $$source)) {
            /**
             * @member
             * @type {Site}
             */
            this["site"] = (new Site());
        }
        if (!("environments" in $$source)) {
            /**
             * @member
             * @type {Environment[]}
             */
            this["environments"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SiteDetails instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SiteDetails}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType6;
        const $$createField1_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("site" in $$parsedSource) {
            $$parsedSource["site"] = $$createField0_0($$parsedSource["site"]);
        }
        if ("environments" in $$parsedSource) {
            $$parsedSource["environments"] = $$createField1_0($$parsedSource["environments"]);
        }
        return new SiteDetails(/** @type {Partial<SiteDetails>} */($$parsedSource));
    }
}

/**
 * Theme represents a WordPress theme (from /wp-themes).
 */
export class Theme {
    /**
     * Creates a new Theme instance.
     * @param {Partial<Theme>} [$$source = {}] - The source object to create the Theme.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("update" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["update"] = "";
        }
        if (!("update_version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["update_version"] = "";
        }
        if (!("is_version_vulnerable" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["is_version_vulnerable"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Theme instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Theme}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Theme(/** @type {Partial<Theme>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = ContainerInfo.createFrom;
const $$createType1 = SSHConnection.createFrom;
const $$createType2 = Plugin.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = Theme.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = Site.createFrom;
const $$createType7 = Environment.createFrom;
const $$createType8 = $Create.Array($$createType7);
