// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export {
    Cel,
    Kolom,
    NieuweWaarde,
    Resultaat,
    SleutelWaarde,
    Tabel
} from "./models.js";
