// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Cel is één waarde uit een resultaat. Null is apart van een lege string, want in
 * een database is dat een wezenlijk verschil dat je in een editor moet zien.
 */
export class Cel {
    "waarde": string;
    "null": boolean;
    "binair": boolean;
    "bytes": number;
    "afgekapt": boolean;

    /** Creates a new Cel instance. */
    constructor($$source: Partial<Cel> = {}) {
        if (!("waarde" in $$source)) {
            this["waarde"] = "";
        }
        if (!("null" in $$source)) {
            this["null"] = false;
        }
        if (!("binair" in $$source)) {
            this["binair"] = false;
        }
        if (!("bytes" in $$source)) {
            this["bytes"] = 0;
        }
        if (!("afgekapt" in $$source)) {
            this["afgekapt"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Cel instance from a string or object.
     */
    static createFrom($$source: any = {}): Cel {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Cel($$parsedSource as Partial<Cel>);
    }
}

/**
 * Kolom beschrijft één kolom.
 */
export class Kolom {
    "naam": string;
    "type": string;
    "nullable": boolean;
    "isPk": boolean;
    "standaard": string;
    "autoIncr": boolean;
    "commentaar": string;

    /** Creates a new Kolom instance. */
    constructor($$source: Partial<Kolom> = {}) {
        if (!("naam" in $$source)) {
            this["naam"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("nullable" in $$source)) {
            this["nullable"] = false;
        }
        if (!("isPk" in $$source)) {
            this["isPk"] = false;
        }
        if (!("standaard" in $$source)) {
            this["standaard"] = "";
        }
        if (!("autoIncr" in $$source)) {
            this["autoIncr"] = false;
        }
        if (!("commentaar" in $$source)) {
            this["commentaar"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Kolom instance from a string or object.
     */
    static createFrom($$source: any = {}): Kolom {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Kolom($$parsedSource as Partial<Kolom>);
    }
}

/**
 * NieuweWaarde is één kolom met de in te voegen waarde.
 */
export class NieuweWaarde {
    "kolom": string;
    "waarde": string;
    "null": boolean;

    /** Creates a new NieuweWaarde instance. */
    constructor($$source: Partial<NieuweWaarde> = {}) {
        if (!("kolom" in $$source)) {
            this["kolom"] = "";
        }
        if (!("waarde" in $$source)) {
            this["waarde"] = "";
        }
        if (!("null" in $$source)) {
            this["null"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NieuweWaarde instance from a string or object.
     */
    static createFrom($$source: any = {}): NieuweWaarde {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NieuweWaarde($$parsedSource as Partial<NieuweWaarde>);
    }
}

/**
 * Resultaat is een resultaatset.
 */
export class Resultaat {
    "kolommen": string[];
    "rijen": Cel[][];

    /**
     * Afgekapt is true als er meer rijen waren dan het maximum.
     */
    "afgekapt": boolean;

    /**
     * Duur is hoe lang de query deed, voor de statusregel.
     */
    "duurMs": number;

    /** Creates a new Resultaat instance. */
    constructor($$source: Partial<Resultaat> = {}) {
        if (!("kolommen" in $$source)) {
            this["kolommen"] = [];
        }
        if (!("rijen" in $$source)) {
            this["rijen"] = [];
        }
        if (!("afgekapt" in $$source)) {
            this["afgekapt"] = false;
        }
        if (!("duurMs" in $$source)) {
            this["duurMs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Resultaat instance from a string or object.
     */
    static createFrom($$source: any = {}): Resultaat {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("kolommen" in $$parsedSource) {
            $$parsedSource["kolommen"] = $$createField0_0($$parsedSource["kolommen"]);
        }
        if ("rijen" in $$parsedSource) {
            $$parsedSource["rijen"] = $$createField1_0($$parsedSource["rijen"]);
        }
        return new Resultaat($$parsedSource as Partial<Resultaat>);
    }
}

/**
 * SleutelWaarde is één primary-key-kolom met zijn waarde.
 */
export class SleutelWaarde {
    "kolom": string;
    "waarde": string;
    "null": boolean;

    /** Creates a new SleutelWaarde instance. */
    constructor($$source: Partial<SleutelWaarde> = {}) {
        if (!("kolom" in $$source)) {
            this["kolom"] = "";
        }
        if (!("waarde" in $$source)) {
            this["waarde"] = "";
        }
        if (!("null" in $$source)) {
            this["null"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SleutelWaarde instance from a string or object.
     */
    static createFrom($$source: any = {}): SleutelWaarde {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SleutelWaarde($$parsedSource as Partial<SleutelWaarde>);
    }
}

/**
 * Tabel is één tabel met wat je nodig hebt om te beslissen of je erin wil kijken.
 */
export class Tabel {
    "naam": string;

    /**
     * Rijen is de schatting uit information_schema; voor InnoDB is die niet
     * exact, en dat staat er in de UI ook bij.
     */
    "rijen": number;
    "bytes": number;
    "engine": string;
    "collation": string;
    "primaryKeys": string[];

    /** Creates a new Tabel instance. */
    constructor($$source: Partial<Tabel> = {}) {
        if (!("naam" in $$source)) {
            this["naam"] = "";
        }
        if (!("rijen" in $$source)) {
            this["rijen"] = 0;
        }
        if (!("bytes" in $$source)) {
            this["bytes"] = 0;
        }
        if (!("engine" in $$source)) {
            this["engine"] = "";
        }
        if (!("collation" in $$source)) {
            this["collation"] = "";
        }
        if (!("primaryKeys" in $$source)) {
            this["primaryKeys"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Tabel instance from a string or object.
     */
    static createFrom($$source: any = {}): Tabel {
        const $$createField5_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("primaryKeys" in $$parsedSource) {
            $$parsedSource["primaryKeys"] = $$createField5_0($$parsedSource["primaryKeys"]);
        }
        return new Tabel($$parsedSource as Partial<Tabel>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = Cel.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Array($$createType2);
