// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * FetchAll runs git fetch in parallel across all projects that are git repos.
 */
export function FetchAll(): $CancellablePromise<$models.BatchResult[]> {
    return $Call.ByID(5736726).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * PullAll runs git pull in parallel across all projects that are git repos.
 */
export function PullAll(): $CancellablePromise<$models.BatchResult[]> {
    return $Call.ByID(3493976717).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.BatchResult.createFrom;
const $$createType1 = $Create.Array($$createType0);
