// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BulkUpdateService werkt alle WordPress-projecten in één run bij vanuit de
 * referentie-installatie: de betaalde plugins én WordPress core. Per project is
 * dat dezelfde route als de losse plugin-update — openstaand werk stashen, een
 * branch aftakken van de verse remote-stand, committen, pushen, PR openen —
 * maar hier over de hele portefeuille in één keer.
 * 
 * Mergen zit er bewust niet in: dat blijft een losse keuze per project, want een
 * bulk-merge naar productiebranches is geen knop die je per ongeluk indrukt.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Plan geeft de voorbeschouwing: per project welke plugins en welke
 * core-versie er bijgewerkt zouden worden. Niets wordt gewijzigd — dit is wat
 * de gebruiker te zien krijgt vóór hij een run start.
 */
export function Plan(): $CancellablePromise<$models.BulkUpdatePlan> {
    return $Call.ByID(3959256299).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Run werkt de gekozen projecten bij. Elk project is onafhankelijk: een
 * mislukking bij het ene stopt de rest niet, en elk project krijgt zijn eigen
 * branch, commit(s) en pull request.
 */
export function Run(projectIDs: string[]): $CancellablePromise<$models.BulkUpdateResult> {
    return $Call.ByID(3996931021, projectIDs).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * SetApp injects the Wails app reference (called after app creation).
 */
export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(878265427, app);
}

// Private type creation functions
const $$createType0 = $models.BulkUpdatePlan.createFrom;
const $$createType1 = $models.BulkUpdateResult.createFrom;
