// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DBCloneService clones a Kinsta project's production database into the
 * developer's own local docker MySQL, rewriting URLs on the way. The
 * production database is only ever read from — every SSH command it sends is
 * built by db_clone_commands.go, which is covered by a guard test that fails
 * if any of those commands could mutate the remote database.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../domain/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../wailsapp/wails/v3/pkg/application/models.js";

/**
 * Clone runs the full pipeline: back up the current local database, export a
 * URL-rewritten dump from production (read-only), download it, import it
 * locally, and — for multisite — fix up the two bare-domain columns that a
 * full-URL search-replace cannot reach.
 */
export function Clone(projectID: string, envID: string, req: domain$0.DBCloneRequest): $CancellablePromise<domain$0.DBCloneResult> {
    return $Call.ByID(2777004495, projectID, envID, req).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * backupIfExists dumps the current local database before it gets overwritten,
 * unless it doesn't exist yet or has no tables. Returns the backup path (or
 * empty) and an optional warning to surface in the result. dbName is already
 * validated by Clone before this is called; re-checked here too (defense in
 * depth), the same way importLocal does.
 * DumpLocal maakt een dump van een lokale database van dit project, op dezelfde
 * plek en met dezelfde bewaartermijn als de backup vóór een kloon. Het pad is
 * leeg met een melding als er nog niets te dumpen was.
 * 
 * Dit hangt hier en niet in de database-editor omdat het dezelfde code is: één
 * plek die weet hoe een lokale dump gemaakt en opgeruimd wordt.
 */
export function DumpLocal(projectID: string, dbName: string): $CancellablePromise<[string, string]> {
    return $Call.ByID(4161516395, projectID, dbName);
}

/**
 * InspectSensitiveData reads the production database's table list and reports
 * which tables hold personal data, which roles exist and how many users there
 * are. Read-only: this only looks.
 */
export function InspectSensitiveData(projectID: string, envID: string): $CancellablePromise<domain$0.SensitiveDataReport> {
    return $Call.ByID(1276480098, projectID, envID).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * LocalDefaults reads the project's own .env file — no SSH involved — to
 * prefill the target fields in the UI.
 */
export function LocalDefaults(projectID: string): $CancellablePromise<domain$0.LocalEnvDefaults> {
    return $Call.ByID(2351475411, projectID).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * OpenInApp opens a local connection to the just-cloned database in the
 * user's configured database program. No password ever reaches the frontend:
 * this method resolves it itself from the project's .env.
 */
export function OpenInApp(projectID: string, localDBHost: string, localDBName: string, appName: string): $CancellablePromise<void> {
    return $Call.ByID(371616532, projectID, localDBHost, localDBName, appName);
}

/**
 * Probe checks what a clone would involve: the canonical site URL, table
 * prefix, multisite status, and database size.
 */
export function Probe(projectID: string, envID: string): $CancellablePromise<domain$0.DBProbe> {
    return $Call.ByID(2383753972, projectID, envID).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * RestoreBackup re-imports a previously taken local backup. backupPath must
 * live under this project's own backup directory — anything else, including
 * any ".." traversal, is refused.
 */
export function RestoreBackup(projectID: string, backupPath: string): $CancellablePromise<void> {
    return $Call.ByID(2189314782, projectID, backupPath);
}

/**
 * SaveLocalURL writes the local URL into deploy_conf.json's link.local
 * (uncommitted — that's the caller's own choice) and refreshes the in-memory
 * project cache so the UI sees it immediately.
 */
export function SaveLocalURL(projectID: string, url: string): $CancellablePromise<void> {
    return $Call.ByID(3758224391, projectID, url);
}

/**
 * SetApp wires the Wails event emitter used for clone progress.
 */
export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(1941145209, app);
}

// Private type creation functions
const $$createType0 = domain$0.DBCloneResult.createFrom;
const $$createType1 = domain$0.SensitiveDataReport.createFrom;
const $$createType2 = domain$0.LocalEnvDefaults.createFrom;
const $$createType3 = domain$0.DBProbe.createFrom;
