// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DBEditorService is een databaseclient voor de lokale ontwikkeldatabase van een
 * project.
 * 
 * Twee dingen liggen hier vast en zijn geen instelling. Er wordt alleen met een
 * lokale host verbonden — de adapter weigert al het andere — en waarden gaan
 * altijd als placeholder mee in plaats van in een SQL-string. Dat laatste is
 * waarom hier geen escaping-code staat: die is er niet, en hoort er niet te komen.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as mysqldb$0 from "../adapters/mysqldb/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * BeoordeelQuery zegt wat een query zou doen, zonder hem uit te voeren. De UI
 * gebruikt dit om de knop en de bevestigingstekst te bepalen.
 */
export function BeoordeelQuery(sqlTekst: string): $CancellablePromise<$models.SQLBeoordeling> {
    return $Call.ByID(868653285, sqlTekst).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * BouwQuery zet een vraag in natuurlijke taal om in een query, zonder die uit te
 * voeren.
 * 
 * Naar de AI gaat alleen het schema: tabelnamen, kolomnamen en types. Er gaat
 * geen enkele rij mee. Dat is belangrijk omdat een gekloonde klantdatabase
 * persoonsgegevens bevat; het schema zegt niets over personen.
 */
export function BouwQuery(projectID: string, dbNaam: string, vraag: string): $CancellablePromise<$models.AIQueryVoorstel> {
    return $Call.ByID(1471297271, projectID, dbNaam, vraag).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Databases geeft de databases op de server van dit project.
 */
export function Databases(projectID: string): $CancellablePromise<string[]> {
    return $Call.ByID(3479855168, projectID).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * Info kijkt of dit project een lokale database heeft. De frontend gebruikt dit
 * om het menu-item te tonen of weg te laten.
 */
export function Info(projectID: string): $CancellablePromise<$models.DBEditorInfo> {
    return $Call.ByID(358338286, projectID).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * MaakDump maakt op verzoek een dump, los van het automatische vangnet.
 */
export function MaakDump(projectID: string, dbNaam: string): $CancellablePromise<$models.SchrijfUitkomst> {
    return $Call.ByID(1663707126, projectID, dbNaam).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * Sluit verbreekt alle verbindingen; bedoeld voor het afsluiten van de app.
 */
export function Sluit(): $CancellablePromise<void> {
    return $Call.ByID(349337329);
}

/**
 * Tabel geeft één tabel met kolommen, een pagina rijen en het totaal.
 */
export function Tabel(projectID: string, v: $models.RijenVerzoek): $CancellablePromise<$models.TabelWeergave> {
    return $Call.ByID(4060098780, projectID, v).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * Tabellen geeft de tabellen van één database.
 */
export function Tabellen(projectID: string, dbNaam: string): $CancellablePromise<mysqldb$0.Tabel[]> {
    return $Call.ByID(1999878995, projectID, dbNaam).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * VerwijderRij verwijdert precies één rij.
 */
export function VerwijderRij(projectID: string, v: $models.RijVerzoek): $CancellablePromise<$models.SchrijfUitkomst> {
    return $Call.ByID(1178526199, projectID, v).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * VoegRijToe voegt een rij toe.
 */
export function VoegRijToe(projectID: string, v: $models.RijVerzoek): $CancellablePromise<$models.SchrijfUitkomst> {
    return $Call.ByID(3688467790, projectID, v).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * VoerQueryUit draait een handmatige query.
 * 
 * Een query die bevestiging vereist wordt niet uitgevoerd zolang bevestigd false
 * is; de UI krijgt dan de reden terug en kan het vragen. De poort zit hier en
 * niet alleen in de frontend, zodat een losse aanroep hem niet overslaat.
 */
export function VoerQueryUit(projectID: string, dbNaam: string, sqlTekst: string, bevestigd: boolean): $CancellablePromise<$models.QueryUitkomst> {
    return $Call.ByID(954925816, projectID, dbNaam, sqlTekst, bevestigd).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * ZetCel slaat één celwijziging op.
 */
export function ZetCel(projectID: string, v: $models.CelVerzoek): $CancellablePromise<$models.SchrijfUitkomst> {
    return $Call.ByID(1102388051, projectID, v).then(($result: any) => {
        return $$createType4($result);
    });
}

// Private type creation functions
const $$createType0 = $models.SQLBeoordeling.createFrom;
const $$createType1 = $models.AIQueryVoorstel.createFrom;
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = $models.DBEditorInfo.createFrom;
const $$createType4 = $models.SchrijfUitkomst.createFrom;
const $$createType5 = $models.TabelWeergave.createFrom;
const $$createType6 = mysqldb$0.Tabel.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = $models.QueryUitkomst.createFrom;
