// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * GetEditor returns the currently configured editor slug.
 * @returns {$CancellablePromise<string>}
 */
export function GetEditor() {
    return $Call.ByID(1853728225);
}

/**
 * OpenInEditor opens the project path in the configured editor.
 * @param {string} projectID
 * @param {string} projectPath
 * @returns {$CancellablePromise<void>}
 */
export function OpenInEditor(projectID, projectPath) {
    return $Call.ByID(3310406550, projectID, projectPath);
}

/**
 * SetEditor updates the configured editor and saves config.
 * @param {string} editor
 * @returns {$CancellablePromise<void>}
 */
export function SetEditor(editor) {
    return $Call.ByID(3775787885, editor);
}
