// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * GitService exposes git operations scoped to a project by ID.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../domain/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AbortMerge aborts an in-progress merge.
 */
export function AbortMerge(projectID: string): $CancellablePromise<void> {
    return $Call.ByID(1736333663, projectID);
}

/**
 * CheckoutBranch checks out the named branch.
 */
export function CheckoutBranch(projectID: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(1361874869, projectID, name);
}

/**
 * Commit creates a commit with the given message, optionally amending.
 */
export function Commit(projectID: string, message: string, amend: boolean): $CancellablePromise<void> {
    return $Call.ByID(356529544, projectID, message, amend);
}

/**
 * CreateBranch creates a new branch, optionally from a specific starting point.
 */
export function CreateBranch(projectID: string, name: string, $from: string): $CancellablePromise<void> {
    return $Call.ByID(2232817977, projectID, name, $from);
}

/**
 * DeleteBranch deletes a branch; force=true skips the safety check.
 */
export function DeleteBranch(projectID: string, name: string, force: boolean): $CancellablePromise<void> {
    return $Call.ByID(663519302, projectID, name, force);
}

/**
 * DiscardFile discards working-tree changes for a tracked file.
 */
export function DiscardFile(projectID: string, filePath: string): $CancellablePromise<void> {
    return $Call.ByID(542010227, projectID, filePath);
}

/**
 * Fetch runs git fetch --all --prune.
 */
export function Fetch(projectID: string): $CancellablePromise<void> {
    return $Call.ByID(1005656831, projectID);
}

/**
 * GetBlame returns per-line blame for a file.
 */
export function GetBlame(projectID: string, filePath: string): $CancellablePromise<domain$0.BlameLine[]> {
    return $Call.ByID(1124260794, projectID, filePath).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetBranches returns all local and remote branches.
 */
export function GetBranches(projectID: string): $CancellablePromise<domain$0.Branch[]> {
    return $Call.ByID(1847984507, projectID).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetCommitDiff returns file diffs for a specific commit.
 */
export function GetCommitDiff(projectID: string, hash: string): $CancellablePromise<domain$0.FileDiff[]> {
    return $Call.ByID(1662677969, projectID, hash).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * GetFileHistory returns the commit log for a specific file.
 */
export function GetFileHistory(projectID: string, filePath: string): $CancellablePromise<domain$0.Commit[]> {
    return $Call.ByID(474647799, projectID, filePath).then(($result: any) => {
        return $$createType7($result);
    });
}

export function GetFiles(projectID: string): $CancellablePromise<string[]> {
    return $Call.ByID(3416233210, projectID).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * GetHistory returns the commit graph for a project.
 */
export function GetHistory(projectID: string, limit: number): $CancellablePromise<domain$0.GraphCommit[]> {
    return $Call.ByID(516582989, projectID, limit).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * GetStashes returns all stash entries for a project.
 */
export function GetStashes(projectID: string): $CancellablePromise<domain$0.Stash[]> {
    return $Call.ByID(2529860440, projectID).then(($result: any) => {
        return $$createType12($result);
    });
}

/**
 * GetStatus returns the current git status for a project.
 */
export function GetStatus(projectID: string): $CancellablePromise<domain$0.GitStatus> {
    return $Call.ByID(2028679045, projectID).then(($result: any) => {
        return $$createType13($result);
    });
}

/**
 * GetTags returns all tags sorted by version/refname descending.
 */
export function GetTags(projectID: string): $CancellablePromise<domain$0.Tag[]> {
    return $Call.ByID(1213701382, projectID).then(($result: any) => {
        return $$createType15($result);
    });
}

/**
 * GetUpdateBranches returns remote branches matching known update branch patterns, sorted newest first.
 */
export function GetUpdateBranches(projectID: string): $CancellablePromise<$models.UpdateBranch[]> {
    return $Call.ByID(1569232410, projectID).then(($result: any) => {
        return $$createType17($result);
    });
}

/**
 * GetWorkingDiff returns staged or unstaged diffs for the working tree.
 */
export function GetWorkingDiff(projectID: string, staged: boolean): $CancellablePromise<domain$0.FileDiff[]> {
    return $Call.ByID(2969255449, projectID, staged).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * MergeBranch merges the named branch into the current branch.
 */
export function MergeBranch(projectID: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(1251418611, projectID, name);
}

/**
 * Pull runs git pull.
 */
export function Pull(projectID: string): $CancellablePromise<void> {
    return $Call.ByID(1914138674, projectID);
}

/**
 * Push pushes the current branch to its upstream remote.
 * It resolves the remote and branch from git status.
 */
export function Push(projectID: string, force: boolean): $CancellablePromise<void> {
    return $Call.ByID(1881024721, projectID, force);
}

/**
 * StageAll stages all changes (git add -A).
 */
export function StageAll(projectID: string): $CancellablePromise<void> {
    return $Call.ByID(2294954976, projectID);
}

/**
 * StageFiles stages the given file paths.
 */
export function StageFiles(projectID: string, paths: string[]): $CancellablePromise<void> {
    return $Call.ByID(3675207236, projectID, paths);
}

/**
 * StashDrop removes stash@{index} without applying it.
 */
export function StashDrop(projectID: string, index: number): $CancellablePromise<void> {
    return $Call.ByID(3788219299, projectID, index);
}

/**
 * StashPop applies and removes stash@{index}.
 */
export function StashPop(projectID: string, index: number): $CancellablePromise<void> {
    return $Call.ByID(662276285, projectID, index);
}

/**
 * StashSave creates a new stash entry.
 */
export function StashSave(projectID: string, message: string): $CancellablePromise<void> {
    return $Call.ByID(780433595, projectID, message);
}

/**
 * UnstageFiles removes the given files from the staging area.
 */
export function UnstageFiles(projectID: string, paths: string[]): $CancellablePromise<void> {
    return $Call.ByID(3987699631, projectID, paths);
}

// Private type creation functions
const $$createType0 = domain$0.BlameLine.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = domain$0.Branch.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = domain$0.FileDiff.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = domain$0.Commit.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = $Create.Array($Create.Any);
const $$createType9 = domain$0.GraphCommit.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = domain$0.Stash.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = domain$0.GitStatus.createFrom;
const $$createType14 = domain$0.Tag.createFrom;
const $$createType15 = $Create.Array($$createType14);
const $$createType16 = $models.UpdateBranch.createFrom;
const $$createType17 = $Create.Array($$createType16);
