// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * GitService exposes git operations scoped to a project by ID.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../domain/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AbortMerge aborts an in-progress merge.
 * @param {string} projectID
 * @returns {$CancellablePromise<void>}
 */
export function AbortMerge(projectID) {
    return $Call.ByID(1736333663, projectID);
}

/**
 * CheckoutBranch checks out the named branch.
 * @param {string} projectID
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function CheckoutBranch(projectID, name) {
    return $Call.ByID(1361874869, projectID, name);
}

/**
 * Commit creates a commit with the given message, optionally amending.
 * @param {string} projectID
 * @param {string} message
 * @param {boolean} amend
 * @returns {$CancellablePromise<void>}
 */
export function Commit(projectID, message, amend) {
    return $Call.ByID(356529544, projectID, message, amend);
}

/**
 * CreateBranch creates a new branch, optionally from a specific starting point.
 * @param {string} projectID
 * @param {string} name
 * @param {string} $from
 * @returns {$CancellablePromise<void>}
 */
export function CreateBranch(projectID, name, $from) {
    return $Call.ByID(2232817977, projectID, name, $from);
}

/**
 * DeleteBranch deletes a branch; force=true skips the safety check.
 * @param {string} projectID
 * @param {string} name
 * @param {boolean} force
 * @returns {$CancellablePromise<void>}
 */
export function DeleteBranch(projectID, name, force) {
    return $Call.ByID(663519302, projectID, name, force);
}

/**
 * DiscardFile discards working-tree changes for a tracked file.
 * @param {string} projectID
 * @param {string} filePath
 * @returns {$CancellablePromise<void>}
 */
export function DiscardFile(projectID, filePath) {
    return $Call.ByID(542010227, projectID, filePath);
}

/**
 * Fetch runs git fetch --all --prune.
 * @param {string} projectID
 * @returns {$CancellablePromise<void>}
 */
export function Fetch(projectID) {
    return $Call.ByID(1005656831, projectID);
}

/**
 * GetBlame returns per-line blame for a file.
 * @param {string} projectID
 * @param {string} filePath
 * @returns {$CancellablePromise<domain$0.BlameLine[]>}
 */
export function GetBlame(projectID, filePath) {
    return $Call.ByID(1124260794, projectID, filePath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetBranches returns all local and remote branches.
 * @param {string} projectID
 * @returns {$CancellablePromise<domain$0.Branch[]>}
 */
export function GetBranches(projectID) {
    return $Call.ByID(1847984507, projectID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * GetCommitDiff returns file diffs for a specific commit.
 * @param {string} projectID
 * @param {string} hash
 * @returns {$CancellablePromise<domain$0.FileDiff[]>}
 */
export function GetCommitDiff(projectID, hash) {
    return $Call.ByID(1662677969, projectID, hash).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * GetFileHistory returns the commit log for a specific file.
 * @param {string} projectID
 * @param {string} filePath
 * @returns {$CancellablePromise<domain$0.Commit[]>}
 */
export function GetFileHistory(projectID, filePath) {
    return $Call.ByID(474647799, projectID, filePath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * @param {string} projectID
 * @returns {$CancellablePromise<string[]>}
 */
export function GetFiles(projectID) {
    return $Call.ByID(3416233210, projectID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * GetHistory returns the commit graph for a project.
 * @param {string} projectID
 * @param {number} limit
 * @returns {$CancellablePromise<domain$0.GraphCommit[]>}
 */
export function GetHistory(projectID, limit) {
    return $Call.ByID(516582989, projectID, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * GetStashes returns all stash entries for a project.
 * @param {string} projectID
 * @returns {$CancellablePromise<domain$0.Stash[]>}
 */
export function GetStashes(projectID) {
    return $Call.ByID(2529860440, projectID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

/**
 * GetStatus returns the current git status for a project.
 * @param {string} projectID
 * @returns {$CancellablePromise<domain$0.GitStatus>}
 */
export function GetStatus(projectID) {
    return $Call.ByID(2028679045, projectID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType13($result);
    }));
}

/**
 * GetTags returns all tags sorted by version/refname descending.
 * @param {string} projectID
 * @returns {$CancellablePromise<domain$0.Tag[]>}
 */
export function GetTags(projectID) {
    return $Call.ByID(1213701382, projectID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType15($result);
    }));
}

/**
 * GetUpdateBranchDetail resolves all updates carried by an update branch,
 * preferring the .updates.json manifest and falling back to the text log +
 * package.json diff. Read-only.
 * @param {string} projectID
 * @param {string} shortName
 * @returns {$CancellablePromise<$models.UpdateDetail | null>}
 */
export function GetUpdateBranchDetail(projectID, shortName) {
    return $Call.ByID(3238847531, projectID, shortName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType17($result);
    }));
}

/**
 * GetUpdateBranches returns remote branches matching known update branch patterns, sorted newest first.
 * @param {string} projectID
 * @returns {$CancellablePromise<$models.UpdateBranch[]>}
 */
export function GetUpdateBranches(projectID) {
    return $Call.ByID(1569232410, projectID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType19($result);
    }));
}

/**
 * GetWorkingDiff returns staged or unstaged diffs for the working tree.
 * @param {string} projectID
 * @param {boolean} staged
 * @returns {$CancellablePromise<domain$0.FileDiff[]>}
 */
export function GetWorkingDiff(projectID, staged) {
    return $Call.ByID(2969255449, projectID, staged).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * MergeBranch merges the named branch into the current branch.
 * @param {string} projectID
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function MergeBranch(projectID, name) {
    return $Call.ByID(1251418611, projectID, name);
}

/**
 * Pull runs git pull.
 * @param {string} projectID
 * @returns {$CancellablePromise<void>}
 */
export function Pull(projectID) {
    return $Call.ByID(1914138674, projectID);
}

/**
 * Push pushes the current branch to its upstream remote.
 * It resolves the remote and branch from git status.
 * @param {string} projectID
 * @param {boolean} force
 * @returns {$CancellablePromise<void>}
 */
export function Push(projectID, force) {
    return $Call.ByID(1881024721, projectID, force);
}

/**
 * StageAll stages all changes (git add -A).
 * @param {string} projectID
 * @returns {$CancellablePromise<void>}
 */
export function StageAll(projectID) {
    return $Call.ByID(2294954976, projectID);
}

/**
 * StageFiles stages the given file paths.
 * @param {string} projectID
 * @param {string[]} paths
 * @returns {$CancellablePromise<void>}
 */
export function StageFiles(projectID, paths) {
    return $Call.ByID(3675207236, projectID, paths);
}

/**
 * StashDrop removes stash@{index} without applying it.
 * @param {string} projectID
 * @param {number} index
 * @returns {$CancellablePromise<void>}
 */
export function StashDrop(projectID, index) {
    return $Call.ByID(3788219299, projectID, index);
}

/**
 * StashPop applies and removes stash@{index}.
 * @param {string} projectID
 * @param {number} index
 * @returns {$CancellablePromise<void>}
 */
export function StashPop(projectID, index) {
    return $Call.ByID(662276285, projectID, index);
}

/**
 * StashSave creates a new stash entry.
 * @param {string} projectID
 * @param {string} message
 * @returns {$CancellablePromise<void>}
 */
export function StashSave(projectID, message) {
    return $Call.ByID(780433595, projectID, message);
}

/**
 * UnstageFiles removes the given files from the staging area.
 * @param {string} projectID
 * @param {string[]} paths
 * @returns {$CancellablePromise<void>}
 */
export function UnstageFiles(projectID, paths) {
    return $Call.ByID(3987699631, projectID, paths);
}

// Private type creation functions
const $$createType0 = domain$0.BlameLine.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = domain$0.Branch.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = domain$0.FileDiff.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = domain$0.Commit.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = $Create.Array($Create.Any);
const $$createType9 = domain$0.GraphCommit.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = domain$0.Stash.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = domain$0.GitStatus.createFrom;
const $$createType14 = domain$0.Tag.createFrom;
const $$createType15 = $Create.Array($$createType14);
const $$createType16 = $models.UpdateDetail.createFrom;
const $$createType17 = $Create.Nullable($$createType16);
const $$createType18 = $models.UpdateBranch.createFrom;
const $$createType19 = $Create.Array($$createType18);
