// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * InventoryService aggregates plugins, themes, and WP core versions across
 * all scanned projects and annotates them with the latest wp.org version.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Plugins returns every plugin found in any project, with per-project
 * installed versions and the latest wp.org version.
 */
export function Plugins(): $CancellablePromise<$models.InventoryItem[]> {
    return $Call.ByID(1052601419).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Themes returns every theme found in any project, with per-project
 * installed versions and the latest wp.org version.
 */
export function Themes(): $CancellablePromise<$models.InventoryItem[]> {
    return $Call.ByID(2379887539).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * WordPress returns each project's WP core version plus the latest release.
 */
export function WordPress(): $CancellablePromise<$models.WPCoreReport> {
    return $Call.ByID(3839459420).then(($result: any) => {
        return $$createType2($result);
    });
}

// Private type creation functions
const $$createType0 = $models.InventoryItem.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.WPCoreReport.createFrom;
