// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * InventoryService aggregates plugins, themes, and WP core versions across
 * all scanned projects and annotates them with the latest wp.org version.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * FetchAll runs git fetch in every project repository so the
 * origin/<default-branch> refs reflect the current remote state.
 */
export function FetchAll(): $CancellablePromise<$models.FetchAllResult> {
    return $Call.ByID(3773232406).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Plugins returns every plugin found in any project, with per-project
 * installed versions (read from the project's default branch) and the latest
 * wp.org version.
 */
export function Plugins(): $CancellablePromise<$models.InventoryItem[]> {
    return $Call.ByID(1052601419).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * Themes returns every theme found in any project, with per-project
 * installed versions (read from the project's default branch) and the latest
 * wp.org version.
 */
export function Themes(): $CancellablePromise<$models.InventoryItem[]> {
    return $Call.ByID(2379887539).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * WordPress returns each project's WP core version plus the latest release.
 */
export function WordPress(): $CancellablePromise<$models.WPCoreReport> {
    return $Call.ByID(3839459420).then(($result: any) => {
        return $$createType3($result);
    });
}

// Private type creation functions
const $$createType0 = $models.FetchAllResult.createFrom;
const $$createType1 = $models.InventoryItem.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $models.WPCoreReport.createFrom;
