// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as kinsta$0 from "../adapters/kinsta/models.js";

/**
 * GetEnvironmentPluginsAndThemes returns plugins + themes for an environment.
 * The environment details themselves are already included in the SiteDetails response.
 */
export function GetEnvironmentPluginsAndThemes(envID: string): $CancellablePromise<kinsta$0.EnvironmentDetails | null> {
    return $Call.ByID(1998672195, envID).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetLinkedSiteID returns the Kinsta site_id stored in .rdm.yml for a project, or "" if not set.
 */
export function GetLinkedSiteID(projectID: string): $CancellablePromise<string> {
    return $Call.ByID(3817890320, projectID);
}

/**
 * GetSiteDetails fetches site info + full environment details (PHP, WP version, etc.).
 */
export function GetSiteDetails(siteID: string): $CancellablePromise<kinsta$0.SiteDetails | null> {
    return $Call.ByID(2795368366, siteID).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * IsConfigured returns true if the global Kinsta API key is set.
 */
export function IsConfigured(): $CancellablePromise<boolean> {
    return $Call.ByID(3951767345);
}

/**
 * LinkSite saves a Kinsta site_id to the project's .rdm.yml so it persists.
 */
export function LinkSite(projectID: string, siteID: string): $CancellablePromise<void> {
    return $Call.ByID(4229065038, projectID, siteID);
}

/**
 * ListSites returns all Kinsta sites for the configured company.
 */
export function ListSites(): $CancellablePromise<kinsta$0.Site[]> {
    return $Call.ByID(3451855999).then(($result: any) => {
        return $$createType5($result);
    });
}

// Private type creation functions
const $$createType0 = kinsta$0.EnvironmentDetails.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = kinsta$0.SiteDetails.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = kinsta$0.Site.createFrom;
const $$createType5 = $Create.Array($$createType4);
