// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as kinsta$0 from "../adapters/kinsta/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * EnvironmentSSH resolves the SSH endpoint of one environment of the project's
 * linked Kinsta site. An empty envID picks the live environment, or the only one
 * when the site has just a single environment.
 */
export function EnvironmentSSH(projectID: string, envID: string): $CancellablePromise<$models.EnvSSHEndpoint> {
    return $Call.ByID(4023335780, projectID, envID).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetEnvironmentPluginsAndThemes returns plugins + themes for an environment.
 * The environment details themselves are already included in the SiteDetails response.
 */
export function GetEnvironmentPluginsAndThemes(envID: string): $CancellablePromise<kinsta$0.EnvironmentDetails | null> {
    return $Call.ByID(1998672195, envID).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetLinkedSiteID returns the Kinsta site_id stored in .rdm.yml for a project, or "" if not set.
 */
export function GetLinkedSiteID(projectID: string): $CancellablePromise<string> {
    return $Call.ByID(3817890320, projectID);
}

/**
 * GetSiteDetails fetches site info + full environment details (PHP, WP version, etc.).
 */
export function GetSiteDetails(siteID: string): $CancellablePromise<kinsta$0.SiteDetails | null> {
    return $Call.ByID(2795368366, siteID).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * IsConfigured returns true if the global Kinsta API key is set.
 */
export function IsConfigured(): $CancellablePromise<boolean> {
    return $Call.ByID(3951767345);
}

/**
 * LinkSite saves a Kinsta site_id to the project's .rdm.yml so it persists.
 * Linking a site that already belongs to another project is refused: that is how
 * projects end up reading each other's data.
 */
export function LinkSite(projectID: string, siteID: string): $CancellablePromise<void> {
    return $Call.ByID(4229065038, projectID, siteID);
}

/**
 * ListSites returns all Kinsta sites for the configured company.
 */
export function ListSites(): $CancellablePromise<kinsta$0.Site[]> {
    return $Call.ByID(3451855999).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * SiteLinkConflicts lists Kinsta sites linked to more than one project. Such a
 * duplicate is never harmless: both projects then read the same site's PHP
 * version, plugin list and SSH details, so at least one shows another customer's
 * data — including in generated reports.
 */
export function SiteLinkConflicts(): $CancellablePromise<$models.SiteLinkConflict[]> {
    return $Call.ByID(1922175449).then(($result: any) => {
        return $$createType8($result);
    });
}

// Private type creation functions
const $$createType0 = $models.EnvSSHEndpoint.createFrom;
const $$createType1 = kinsta$0.EnvironmentDetails.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = kinsta$0.SiteDetails.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = kinsta$0.Site.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = $models.SiteLinkConflict.createFrom;
const $$createType8 = $Create.Array($$createType7);
