// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as kinsta$0 from "../adapters/kinsta/models.js";

/**
 * GetEnvironmentPluginsAndThemes returns plugins + themes for an environment.
 * The environment details themselves are already included in the SiteDetails response.
 * @param {string} envID
 * @returns {$CancellablePromise<kinsta$0.EnvironmentDetails | null>}
 */
export function GetEnvironmentPluginsAndThemes(envID) {
    return $Call.ByID(1998672195, envID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetLinkedSiteID returns the Kinsta site_id stored in .rdm.yml for a project, or "" if not set.
 * @param {string} projectID
 * @returns {$CancellablePromise<string>}
 */
export function GetLinkedSiteID(projectID) {
    return $Call.ByID(3817890320, projectID);
}

/**
 * GetSiteDetails fetches site info + full environment details (PHP, WP version, etc.).
 * @param {string} siteID
 * @returns {$CancellablePromise<kinsta$0.SiteDetails | null>}
 */
export function GetSiteDetails(siteID) {
    return $Call.ByID(2795368366, siteID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * IsConfigured returns true if the global Kinsta API key is set.
 * @returns {$CancellablePromise<boolean>}
 */
export function IsConfigured() {
    return $Call.ByID(3951767345);
}

/**
 * LinkSite saves a Kinsta site_id to the project's .rdm.yml so it persists.
 * @param {string} projectID
 * @param {string} siteID
 * @returns {$CancellablePromise<void>}
 */
export function LinkSite(projectID, siteID) {
    return $Call.ByID(4229065038, projectID, siteID);
}

/**
 * ListSites returns all Kinsta sites for the configured company.
 * @returns {$CancellablePromise<kinsta$0.Site[]>}
 */
export function ListSites() {
    return $Call.ByID(3451855999).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

// Private type creation functions
const $$createType0 = kinsta$0.EnvironmentDetails.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = kinsta$0.SiteDetails.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = kinsta$0.Site.createFrom;
const $$createType5 = $Create.Array($$createType4);
