// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetTargets parses and returns the .PHONY targets from the Makefile.
 * @param {string} projectID
 * @returns {$CancellablePromise<$models.MakeTarget[]>}
 */
export function GetTargets(projectID) {
    return $Call.ByID(839851465, projectID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * HasMakefile returns true if a Makefile exists in the project root.
 * @param {string} projectID
 * @returns {$CancellablePromise<boolean>}
 */
export function HasMakefile(projectID) {
    return $Call.ByID(2854724829, projectID);
}

/**
 * Run executes `make <target>` in the project directory and returns combined output.
 * @param {string} projectID
 * @param {string} target
 * @returns {$CancellablePromise<$models.MakeResult | null>}
 */
export function Run(projectID, target) {
    return $Call.ByID(4082484660, projectID, target).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.MakeTarget.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.MakeResult.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
