// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetTargets parses and returns the .PHONY targets from the Makefile.
 */
export function GetTargets(projectID: string): $CancellablePromise<$models.MakeTarget[]> {
    return $Call.ByID(839851465, projectID).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * HasMakefile returns true if a Makefile exists in the project root.
 */
export function HasMakefile(projectID: string): $CancellablePromise<boolean> {
    return $Call.ByID(2854724829, projectID);
}

/**
 * Run executes `make <target>` in the project directory and returns combined output.
 */
export function Run(projectID: string, target: string): $CancellablePromise<$models.MakeResult | null> {
    return $Call.ByID(4082484660, projectID, target).then(($result: any) => {
        return $$createType3($result);
    });
}

// Private type creation functions
const $$createType0 = $models.MakeTarget.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.MakeResult.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
