// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MediaService analyses wp-content/uploads on a Kinsta environment: what is there,
 * how big it is, and which media have no reference left. It is deliberately
 * read-only — there is no method here that changes anything on the server.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../domain/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetSSHAccess returns the stored SSH username and webroot for a project.
 */
export function GetSSHAccess(projectID: string): $CancellablePromise<$models.SSHAccess> {
    return $Call.ByID(3789049665, projectID).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * LatestScan returns the newest stored scan, or nil when the project was never
 * scanned.
 */
export function LatestScan(projectID: string): $CancellablePromise<domain$0.MediaScanSummary | null> {
    return $Call.ByID(2408727983, projectID).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * ListScans returns the stored scans, newest first, so growth over time is visible.
 */
export function ListScans(projectID: string): $CancellablePromise<domain$0.MediaScanSummary[]> {
    return $Call.ByID(865308785, projectID).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * ProbeEnvironment checks whether a scan can work at all: does the key-based login
 * succeed, which user are we, where is the site, does WP-CLI answer, and how big is
 * uploads. Cheap enough to run before anything else.
 */
export function ProbeEnvironment(projectID: string, envID: string): $CancellablePromise<$models.MediaProbe> {
    return $Call.ByID(1194297282, projectID, envID).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * SaveSSHAccess stores the SSH username and optional webroot in .rdm.yml. An empty
 * path means: find it on the server during the next scan.
 */
export function SaveSSHAccess(projectID: string, user: string, path: string): $CancellablePromise<void> {
    return $Call.ByID(3968795680, projectID, user, path);
}

/**
 * ScanDetail returns a window of a scan's per-file rows.
 */
export function ScanDetail(projectID: string, scanID: string, offset: number, limit: number): $CancellablePromise<domain$0.MediaFileRow[]> {
    return $Call.ByID(372605205, projectID, scanID, offset, limit).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * ScanEnvironment runs the analyzer on one environment and stores the result. The
 * stored scan is returned so the UI can show it right away.
 */
export function ScanEnvironment(projectID: string, envID: string): $CancellablePromise<domain$0.MediaScanSummary> {
    return $Call.ByID(3796140597, projectID, envID).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.SSHAccess.createFrom;
const $$createType1 = domain$0.MediaScanSummary.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = $Create.Array($$createType1);
const $$createType4 = $models.MediaProbe.createFrom;
const $$createType5 = domain$0.MediaFileRow.createFrom;
const $$createType6 = $Create.Array($$createType5);
