// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MediaService analyses wp-content/uploads on a Kinsta environment: what is there,
 * how big it is, and which media have no reference left. It is deliberately
 * read-only — there is no method here that changes anything on the server.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../domain/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CrawlConflicts lists the files the scan called unreferenced while the crawl saw
 * them being loaded, largest first. These are the files that would have been moved
 * on the database scan alone, so they deserve to be checked by hand.
 */
export function CrawlConflicts(projectID: string, scanID: string, offset: number, limit: number): $CancellablePromise<$models.MediaCrawlConflict[]> {
    return $Call.ByID(4018054447, projectID, scanID, offset, limit).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * CrawlSite visits the live site and records which uploads the browser really
 * requests. Anything it finds is proof of use, so those files are excluded from
 * quarantine from that moment on — regardless of what the database scan concluded.
 */
export function CrawlSite(projectID: string, envID: string, scanID: string, maxPages: number): $CancellablePromise<$models.MediaCrawlResult> {
    return $Call.ByID(4001450055, projectID, envID, scanID, maxPages).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * CrawlSummary returns the stored crawl for a scan without the per-file page lists,
 * so the UI can show the counts without pulling megabytes across the bridge.
 */
export function CrawlSummary(projectID: string, scanID: string): $CancellablePromise<$models.MediaCrawlResult | null> {
    return $Call.ByID(1003076, projectID, scanID).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * FileUsage returns the pages where a crawl saw one file. Empty means: not seen on
 * any page this crawl visited — which is not the same as unused, because a crawl only
 * covers the pages it reached.
 */
export function FileUsage(projectID: string, scanID: string, path: string): $CancellablePromise<string[]> {
    return $Call.ByID(1705440958, projectID, scanID, path).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * GetSSHAccess returns the stored SSH username, webroot and whether a password is
 * on file.
 */
export function GetSSHAccess(projectID: string): $CancellablePromise<$models.SSHAccess> {
    return $Call.ByID(3789049665, projectID).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * LatestScan returns the newest stored scan, or nil when the project was never
 * scanned.
 */
export function LatestScan(projectID: string): $CancellablePromise<domain$0.MediaScanSummary | null> {
    return $Call.ByID(2408727983, projectID).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * ListQuarantine returns the batches currently in quarantine on the server.
 */
export function ListQuarantine(projectID: string, envID: string): $CancellablePromise<$models.QuarantineBatch[]> {
    return $Call.ByID(1492208993, projectID, envID).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * ListScans returns the stored scans, newest first, so growth over time is visible.
 */
export function ListScans(projectID: string): $CancellablePromise<domain$0.MediaScanSummary[]> {
    return $Call.ByID(865308785, projectID).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * ProbeEnvironment checks whether a scan can work at all: does the key-based login
 * succeed, which user are we, where is the site, does WP-CLI answer, and how big is
 * uploads. Cheap enough to run before anything else.
 */
export function ProbeEnvironment(projectID: string, envID: string): $CancellablePromise<$models.MediaProbe> {
    return $Call.ByID(1194297282, projectID, envID).then(($result: any) => {
        return $$createType11($result);
    });
}

/**
 * QuarantineFiles moves the given files out of uploads into a quarantine directory
 * and records a manifest so the whole batch can be put back. Nothing is deleted, and
 * the attachment records in WordPress stay untouched — that is what makes a restore a
 * matter of moving files back.
 * 
 * A path is only accepted when the stored scan itself placed it in a safe category.
 * That check is the real safety net: it means neither a UI bug nor a stale selection
 * can reach a file the scan found in use.
 */
export function QuarantineFiles(projectID: string, envID: string, scanID: string, paths: string[], minAgeDays: number): $CancellablePromise<$models.QuarantineResult> {
    return $Call.ByID(3473416408, projectID, envID, scanID, paths, minAgeDays).then(($result: any) => {
        return $$createType12($result);
    });
}

/**
 * RestoreQuarantine puts a whole batch back where it came from. Files whose original
 * place is occupied again are left in quarantine and reported, never overwritten.
 */
export function RestoreQuarantine(projectID: string, envID: string, batch: string): $CancellablePromise<$models.QuarantineResult> {
    return $Call.ByID(3271340281, projectID, envID, batch).then(($result: any) => {
        return $$createType12($result);
    });
}

/**
 * SaveSSHAccess stores the SSH username and optional webroot in .rdm/config.yml. An empty
 * path means: find it on the server during the next scan. A non-empty password goes
 * into the macOS keychain and only a reference to it is written to .rdm/config.yml —
 * that file is committed in the customer's repo, so the secret can never live
 * there. An empty password leaves any stored one untouched.
 */
export function SaveSSHAccess(projectID: string, user: string, path: string, password: string): $CancellablePromise<void> {
    return $Call.ByID(3968795680, projectID, user, path, password);
}

/**
 * ScanDetail returns a window of the stored rows, narrowed by category and/or folder.
 * Both filters matter for paging: the detail file holds every category and every
 * folder in one stream, so an offset only means something once the filter is applied.
 * An empty category or prefix means "no restriction".
 */
export function ScanDetail(projectID: string, scanID: string, category: domain$0.MediaCategory, prefix: string, offset: number, limit: number): $CancellablePromise<domain$0.MediaFileRow[]> {
    return $Call.ByID(372605205, projectID, scanID, category, prefix, offset, limit).then(($result: any) => {
        return $$createType14($result);
    });
}

/**
 * ScanEnvironment runs the analyzer on one environment and stores the result. When
 * folders is non-empty the scan is limited to those prefixes inside uploads, which
 * keeps both the file walk and the library index small — the way to look at one
 * year without waiting for a whole media library.
 */
export function ScanEnvironment(projectID: string, envID: string, folders: string[]): $CancellablePromise<domain$0.MediaScanSummary> {
    return $Call.ByID(3796140597, projectID, envID, folders).then(($result: any) => {
        return $$createType6($result);
    });
}

// Private type creation functions
const $$createType0 = $models.MediaCrawlConflict.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.MediaCrawlResult.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Array($Create.Any);
const $$createType5 = $models.SSHAccess.createFrom;
const $$createType6 = domain$0.MediaScanSummary.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = $models.QuarantineBatch.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = $Create.Array($$createType6);
const $$createType11 = $models.MediaProbe.createFrom;
const $$createType12 = $models.QuarantineResult.createFrom;
const $$createType13 = domain$0.MediaFileRow.createFrom;
const $$createType14 = $Create.Array($$createType13);
