// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MigrationService handles pulling a production environment down to a local
 * one: the URL mapping used during a migration, and copying wp-content/uploads
 * from the server into the local checkout. It only ever reads from production.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../domain/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../wailsapp/wails/v3/pkg/application/models.js";

/**
 * GetSettings returns the stored migration mapping. When .rdm.yml has none
 * yet, sensible values are derived from the project's own .env and
 * deploy_conf.json so the form opens filled in rather than blank — but nothing
 * is written until the user saves.
 */
export function GetSettings(projectID: string): $CancellablePromise<domain$0.MigrationCfg> {
    return $Call.ByID(4133690470, projectID).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ListUploadFolders lists the top-level folders inside wp-content/uploads on
 * the server with their sizes, so the user can choose what to pull.
 */
export function ListUploadFolders(projectID: string, envID: string): $CancellablePromise<domain$0.UploadFolder[]> {
    return $Call.ByID(3676206145, projectID, envID).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * LocalUploadsPath is where a pull writes: the uploads folder of the local
 * checkout. That path is covered by the customer repo's .gitignore
 * (/public/wp-content/*), so pulled media can never end up in a commit.
 */
export function LocalUploadsPath(projectID: string): $CancellablePromise<string> {
    return $Call.ByID(2912989481, projectID);
}

/**
 * PullMedia copies the selected uploads folders from production into the local
 * checkout, overwriting what is already there so the local copy matches
 * production exactly.
 * 
 * Each folder is streamed as a gzipped tar straight out of the SSH session and
 * unpacked on the fly, so nothing large is ever written to the customer's
 * server and no full copy has to fit in memory here either.
 */
export function PullMedia(projectID: string, envID: string, folders: string[]): $CancellablePromise<domain$0.MediaPullResult> {
    return $Call.ByID(55358362, projectID, envID, folders).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * SaveSettings writes the migration mapping to .rdm.yml. That file lives in the
 * customer's repo, so this only writes it — committing is the user's own call,
 * same as with deploy_conf.json's link.local.
 */
export function SaveSettings(projectID: string, cfg: domain$0.MigrationCfg): $CancellablePromise<void> {
    return $Call.ByID(1139242833, projectID, cfg);
}

/**
 * SetApp wires the Wails event emitter used for pull progress.
 */
export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(1429225370, app);
}

// Private type creation functions
const $$createType0 = domain$0.MigrationCfg.createFrom;
const $$createType1 = domain$0.UploadFolder.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = domain$0.MediaPullResult.createFrom;
