// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

/**
 * AppSettings is the flat DTO exposed to the frontend.
 */
export class AppSettings {
    /**
     * Creates a new AppSettings instance.
     * @param {Partial<AppSettings>} [$$source = {}] - The source object to create the AppSettings.
     */
    constructor($$source = {}) {
        if (!("editor" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["editor"] = "";
        }
        if (!("kinstaApiKey" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["kinstaApiKey"] = "";
        }
        if (!("kinstaCompanyId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["kinstaCompanyId"] = "";
        }
        if (!("githubToken" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["githubToken"] = "";
        }
        if (!("pluginRepo" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["pluginRepo"] = "";
        }
        if (!("pluginRepoRef" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["pluginRepoRef"] = "";
        }
        if (!("gitDefaultRemote" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["gitDefaultRemote"] = "";
        }
        if (!("gitPruneOnFetch" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["gitPruneOnFetch"] = false;
        }
        if (!("anthropicApiKey" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["anthropicApiKey"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppSettings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AppSettings}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppSettings(/** @type {Partial<AppSettings>} */($$parsedSource));
    }
}

/**
 * BatchResult holds the outcome of a single project operation.
 */
export class BatchResult {
    /**
     * Creates a new BatchResult instance.
     * @param {Partial<BatchResult>} [$$source = {}] - The source object to create the BatchResult.
     */
    constructor($$source = {}) {
        if (!("projectId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["projectId"] = "";
        }
        if (!("displayName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["displayName"] = "";
        }
        if (!("op" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["op"] = "";
        }
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BatchResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BatchResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BatchResult(/** @type {Partial<BatchResult>} */($$parsedSource));
    }
}

/**
 * MakeResult holds the stdout/stderr output of a make invocation.
 */
export class MakeResult {
    /**
     * Creates a new MakeResult instance.
     * @param {Partial<MakeResult>} [$$source = {}] - The source object to create the MakeResult.
     */
    constructor($$source = {}) {
        if (!("target" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["target"] = "";
        }
        if (!("output" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["output"] = "";
        }
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MakeResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MakeResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MakeResult(/** @type {Partial<MakeResult>} */($$parsedSource));
    }
}

/**
 * MakeTarget is a parsed Makefile target.
 */
export class MakeTarget {
    /**
     * Creates a new MakeTarget instance.
     * @param {Partial<MakeTarget>} [$$source = {}] - The source object to create the MakeTarget.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MakeTarget instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MakeTarget}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MakeTarget(/** @type {Partial<MakeTarget>} */($$parsedSource));
    }
}

/**
 * PackageUpdate is a single package version change (or availability).
 */
export class PackageUpdate {
    /**
     * Creates a new PackageUpdate instance.
     * @param {Partial<PackageUpdate>} [$$source = {}] - The source object to create the PackageUpdate.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("from" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["from"] = "";
        }
        if (!("to" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["to"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * "minor" | "patch" (npm applied)
             * @member
             * @type {string | undefined}
             */
            this["type"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * "applied" | "manual" | "" (onbekend)
             * @member
             * @type {string | undefined}
             */
            this["status"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * toelichting bij "manual"
             * @member
             * @type {string | undefined}
             */
            this["reason"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PackageUpdate instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PackageUpdate}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PackageUpdate(/** @type {Partial<PackageUpdate>} */($$parsedSource));
    }
}

/**
 * ProjectWorkflow is een actieve GitHub Actions workflow van een project-repo,
 * met de status van de meest recente run.
 */
export class ProjectWorkflow {
    /**
     * Creates a new ProjectWorkflow instance.
     * @param {Partial<ProjectWorkflow>} [$$source = {}] - The source object to create the ProjectWorkflow.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("runStatus" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["runStatus"] = "";
        }
        if (!("runConclusion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["runConclusion"] = "";
        }
        if (!("runUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["runUrl"] = "";
        }
        if (!("runAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["runAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProjectWorkflow instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProjectWorkflow}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProjectWorkflow(/** @type {Partial<ProjectWorkflow>} */($$parsedSource));
    }
}

/**
 * SearchHit represents a single grep match in a file.
 */
export class SearchHit {
    /**
     * Creates a new SearchHit instance.
     * @param {Partial<SearchHit>} [$$source = {}] - The source object to create the SearchHit.
     */
    constructor($$source = {}) {
        if (!("projectId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["projectId"] = "";
        }
        if (!("displayName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["displayName"] = "";
        }
        if (!("file" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["file"] = "";
        }
        if (!("line" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["line"] = 0;
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchHit instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SearchHit}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SearchHit(/** @type {Partial<SearchHit>} */($$parsedSource));
    }
}

/**
 * SecurityFinding is één kwetsbaarheid uit een composer- of npm-audit.
 */
export class SecurityFinding {
    /**
     * Creates a new SecurityFinding instance.
     * @param {Partial<SecurityFinding>} [$$source = {}] - The source object to create the SecurityFinding.
     */
    constructor($$source = {}) {
        if (!("source" in $$source)) {
            /**
             * "composer" | "npm"
             * @member
             * @type {string}
             */
            this["source"] = "";
        }
        if (!("package" in $$source)) {
            /**
             * pakketnaam
             * @member
             * @type {string}
             */
            this["package"] = "";
        }
        if (!("severity" in $$source)) {
            /**
             * critical | high | moderate/medium | low | unknown
             * @member
             * @type {string}
             */
            this["severity"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("cve" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["cve"] = "";
        }
        if (!("link" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["link"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SecurityFinding instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SecurityFinding}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SecurityFinding(/** @type {Partial<SecurityFinding>} */($$parsedSource));
    }
}

/**
 * SecurityScanResult is de meest recente scan-uitkomst van een project-repo.
 */
export class SecurityScanResult {
    /**
     * Creates a new SecurityScanResult instance.
     * @param {Partial<SecurityScanResult>} [$$source = {}] - The source object to create the SecurityScanResult.
     */
    constructor($$source = {}) {
        if (!("repo" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["repo"] = "";
        }
        if (!("scannedAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["scannedAt"] = null;
        }
        if (!("hasComposerReport" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["hasComposerReport"] = false;
        }
        if (!("hasNpmReport" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["hasNpmReport"] = false;
        }
        if (!("findings" in $$source)) {
            /**
             * @member
             * @type {SecurityFinding[]}
             */
            this["findings"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SecurityScanResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SecurityScanResult}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("findings" in $$parsedSource) {
            $$parsedSource["findings"] = $$createField4_0($$parsedSource["findings"]);
        }
        return new SecurityScanResult(/** @type {Partial<SecurityScanResult>} */($$parsedSource));
    }
}

/**
 * GetFiles returns all tracked files in the repository via git ls-files.
 * UpdateBranch represents a detected automated WordPress update branch.
 */
export class UpdateBranch {
    /**
     * Creates a new UpdateBranch instance.
     * @param {Partial<UpdateBranch>} [$$source = {}] - The source object to create the UpdateBranch.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("shortName" in $$source)) {
            /**
             * without remote prefix
             * @member
             * @type {string}
             */
            this["shortName"] = "";
        }
        if (!("dateStr" in $$source)) {
            /**
             * raw date portion from branch name
             * @member
             * @type {string}
             */
            this["dateStr"] = "";
        }
        if (!("isLocal" in $$source)) {
            /**
             * true if also checked out locally
             * @member
             * @type {boolean}
             */
            this["isLocal"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateBranch instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UpdateBranch}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateBranch(/** @type {Partial<UpdateBranch>} */($$parsedSource));
    }
}

/**
 * UpdateDetail is the fully resolved set of updates inside an update branch.
 */
export class UpdateDetail {
    /**
     * Creates a new UpdateDetail instance.
     * @param {Partial<UpdateDetail>} [$$source = {}] - The source object to create the UpdateDetail.
     */
    constructor($$source = {}) {
        if (!("source" in $$source)) {
            /**
             * "manifest" | "fallback"
             * @member
             * @type {string}
             */
            this["source"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["generatedAt"] = undefined;
        }
        if (!("wpCore" in $$source)) {
            /**
             * @member
             * @type {WPCoreUpdate[]}
             */
            this["wpCore"] = [];
        }
        if (!("wpPlugins" in $$source)) {
            /**
             * @member
             * @type {PackageUpdate[]}
             */
            this["wpPlugins"] = [];
        }
        if (!("wpThemes" in $$source)) {
            /**
             * @member
             * @type {PackageUpdate[]}
             */
            this["wpThemes"] = [];
        }
        if (!("npmApplied" in $$source)) {
            /**
             * @member
             * @type {PackageUpdate[]}
             */
            this["npmApplied"] = [];
        }
        if (!("npmAvailableMajors" in $$source)) {
            /**
             * @member
             * @type {PackageUpdate[]}
             */
            this["npmAvailableMajors"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateDetail instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UpdateDetail}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType3;
        const $$createField3_0 = $$createType5;
        const $$createField4_0 = $$createType5;
        const $$createField5_0 = $$createType5;
        const $$createField6_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("wpCore" in $$parsedSource) {
            $$parsedSource["wpCore"] = $$createField2_0($$parsedSource["wpCore"]);
        }
        if ("wpPlugins" in $$parsedSource) {
            $$parsedSource["wpPlugins"] = $$createField3_0($$parsedSource["wpPlugins"]);
        }
        if ("wpThemes" in $$parsedSource) {
            $$parsedSource["wpThemes"] = $$createField4_0($$parsedSource["wpThemes"]);
        }
        if ("npmApplied" in $$parsedSource) {
            $$parsedSource["npmApplied"] = $$createField5_0($$parsedSource["npmApplied"]);
        }
        if ("npmAvailableMajors" in $$parsedSource) {
            $$parsedSource["npmAvailableMajors"] = $$createField6_0($$parsedSource["npmAvailableMajors"]);
        }
        return new UpdateDetail(/** @type {Partial<UpdateDetail>} */($$parsedSource));
    }
}

/**
 * VulnFinding is a single vulnerable plugin discovered on a Kinsta environment.
 */
export class VulnFinding {
    /**
     * Creates a new VulnFinding instance.
     * @param {Partial<VulnFinding>} [$$source = {}] - The source object to create the VulnFinding.
     */
    constructor($$source = {}) {
        if (!("projectId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["projectId"] = "";
        }
        if (!("projectName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["projectName"] = "";
        }
        if (!("siteId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["siteId"] = "";
        }
        if (!("envId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["envId"] = "";
        }
        if (!("envName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["envName"] = "";
        }
        if (!("slug" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["slug"] = "";
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VulnFinding instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {VulnFinding}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VulnFinding(/** @type {Partial<VulnFinding>} */($$parsedSource));
    }
}

/**
 * WPCoreUpdate is a single WordPress core version availability.
 */
export class WPCoreUpdate {
    /**
     * Creates a new WPCoreUpdate instance.
     * @param {Partial<WPCoreUpdate>} [$$source = {}] - The source object to create the WPCoreUpdate.
     */
    constructor($$source = {}) {
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("updateType" in $$source)) {
            /**
             * "minor" | "major"
             * @member
             * @type {string}
             */
            this["updateType"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["status"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["reason"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WPCoreUpdate instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WPCoreUpdate}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WPCoreUpdate(/** @type {Partial<WPCoreUpdate>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = SecurityFinding.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = WPCoreUpdate.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = PackageUpdate.createFrom;
const $$createType5 = $Create.Array($$createType4);
