// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AppSettings is the flat DTO exposed to the frontend.
 */
export class AppSettings {
    "editor": string;
    "dbApp": string;
    "kinstaApiKey": string;
    "kinstaCompanyId": string;
    "githubToken": string;
    "pluginRepo": string;
    "pluginRepoRef": string;
    "pluginLocalDir": string;
    "gitDefaultRemote": string;
    "gitPruneOnFetch": boolean;
    "anthropicApiKey": string;
    "wordfenceApiKey": string;

    /** Creates a new AppSettings instance. */
    constructor($$source: Partial<AppSettings> = {}) {
        if (!("editor" in $$source)) {
            this["editor"] = "";
        }
        if (!("dbApp" in $$source)) {
            this["dbApp"] = "";
        }
        if (!("kinstaApiKey" in $$source)) {
            this["kinstaApiKey"] = "";
        }
        if (!("kinstaCompanyId" in $$source)) {
            this["kinstaCompanyId"] = "";
        }
        if (!("githubToken" in $$source)) {
            this["githubToken"] = "";
        }
        if (!("pluginRepo" in $$source)) {
            this["pluginRepo"] = "";
        }
        if (!("pluginRepoRef" in $$source)) {
            this["pluginRepoRef"] = "";
        }
        if (!("pluginLocalDir" in $$source)) {
            this["pluginLocalDir"] = "";
        }
        if (!("gitDefaultRemote" in $$source)) {
            this["gitDefaultRemote"] = "";
        }
        if (!("gitPruneOnFetch" in $$source)) {
            this["gitPruneOnFetch"] = false;
        }
        if (!("anthropicApiKey" in $$source)) {
            this["anthropicApiKey"] = "";
        }
        if (!("wordfenceApiKey" in $$source)) {
            this["wordfenceApiKey"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): AppSettings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppSettings($$parsedSource as Partial<AppSettings>);
    }
}

/**
 * BatchResult holds the outcome of a single project operation.
 */
export class BatchResult {
    "projectId": string;
    "displayName": string;
    "op": string;
    "success": boolean;
    "error"?: string;

    /** Creates a new BatchResult instance. */
    constructor($$source: Partial<BatchResult> = {}) {
        if (!("projectId" in $$source)) {
            this["projectId"] = "";
        }
        if (!("displayName" in $$source)) {
            this["displayName"] = "";
        }
        if (!("op" in $$source)) {
            this["op"] = "";
        }
        if (!("success" in $$source)) {
            this["success"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BatchResult instance from a string or object.
     */
    static createFrom($$source: any = {}): BatchResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BatchResult($$parsedSource as Partial<BatchResult>);
    }
}

/**
 * CoreUpdateResult is de uitkomst van één core-update.
 */
export class CoreUpdateResult {
    "projectId": string;
    "projectName": string;

    /**
     * Status: pr_created | exists | skipped_no_release | error
     */
    "status": string;
    "from": string;
    "to": string;
    "branch": string;
    "pullRequestUrl": string;
    "error": string;

    /** Creates a new CoreUpdateResult instance. */
    constructor($$source: Partial<CoreUpdateResult> = {}) {
        if (!("projectId" in $$source)) {
            this["projectId"] = "";
        }
        if (!("projectName" in $$source)) {
            this["projectName"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("from" in $$source)) {
            this["from"] = "";
        }
        if (!("to" in $$source)) {
            this["to"] = "";
        }
        if (!("branch" in $$source)) {
            this["branch"] = "";
        }
        if (!("pullRequestUrl" in $$source)) {
            this["pullRequestUrl"] = "";
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CoreUpdateResult instance from a string or object.
     */
    static createFrom($$source: any = {}): CoreUpdateResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CoreUpdateResult($$parsedSource as Partial<CoreUpdateResult>);
    }
}

/**
 * EnvSSHEndpoint is one environment's SSH endpoint as Kinsta reports it. The API
 * has no username field, so that has to come from the project's own config.
 */
export class EnvSSHEndpoint {
    "host": string;
    "port": number;
    "envName": string;

    /** Creates a new EnvSSHEndpoint instance. */
    constructor($$source: Partial<EnvSSHEndpoint> = {}) {
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("envName" in $$source)) {
            this["envName"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EnvSSHEndpoint instance from a string or object.
     */
    static createFrom($$source: any = {}): EnvSSHEndpoint {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EnvSSHEndpoint($$parsedSource as Partial<EnvSSHEndpoint>);
    }
}

export class FeedMeta {
    "fetchedAt": string;
    "count": number;

    /** Creates a new FeedMeta instance. */
    constructor($$source: Partial<FeedMeta> = {}) {
        if (!("fetchedAt" in $$source)) {
            this["fetchedAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("count" in $$source)) {
            this["count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FeedMeta instance from a string or object.
     */
    static createFrom($$source: any = {}): FeedMeta {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FeedMeta($$parsedSource as Partial<FeedMeta>);
    }
}

/**
 * FetchAllResult summarizes a git fetch across all project repositories.
 */
export class FetchAllResult {
    "fetched": number;
    "errors": string[];

    /** Creates a new FetchAllResult instance. */
    constructor($$source: Partial<FetchAllResult> = {}) {
        if (!("fetched" in $$source)) {
            this["fetched"] = 0;
        }
        if (!("errors" in $$source)) {
            this["errors"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FetchAllResult instance from a string or object.
     */
    static createFrom($$source: any = {}): FetchAllResult {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("errors" in $$parsedSource) {
            $$parsedSource["errors"] = $$createField1_0($$parsedSource["errors"]);
        }
        return new FetchAllResult($$parsedSource as Partial<FetchAllResult>);
    }
}

/**
 * InventoryItem is one plugin or theme aggregated across all projects.
 */
export class InventoryItem {
    "slug": string;
    "latestVersion": string;

    /**
     * wporg | manual
     */
    "source": string;
    "outdatedCount": number;
    "projects": InventoryProjectRef[];

    /** Creates a new InventoryItem instance. */
    constructor($$source: Partial<InventoryItem> = {}) {
        if (!("slug" in $$source)) {
            this["slug"] = "";
        }
        if (!("latestVersion" in $$source)) {
            this["latestVersion"] = "";
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("outdatedCount" in $$source)) {
            this["outdatedCount"] = 0;
        }
        if (!("projects" in $$source)) {
            this["projects"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InventoryItem instance from a string or object.
     */
    static createFrom($$source: any = {}): InventoryItem {
        const $$createField4_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("projects" in $$parsedSource) {
            $$parsedSource["projects"] = $$createField4_0($$parsedSource["projects"]);
        }
        return new InventoryItem($$parsedSource as Partial<InventoryItem>);
    }
}

/**
 * InventoryProjectRef is one project's installed version of an item.
 */
export class InventoryProjectRef {
    "projectId": string;
    "projectName": string;

    /**
     * LocalVersion is de versie in de werkmap van de gebruiker.
     */
    "localVersion": string;

    /**
     * GithubVersion is de versie op de default release-branch van GitHub
     * (gelezen van origin/<branch>, die vooraf wordt bijgewerkt).
     */
    "githubVersion": string;

    /**
     * Outdated vergelijkt de GitHub-kolom met de laatste versie: dat is de
     * stand die naar productie gaat.
     */
    "outdated": boolean;

    /**
     * LocalBehind is true als de werkmap achterloopt op GitHub — een hint om
     * te pullen, niet hetzelfde als verouderd.
     */
    "localBehind": boolean;

    /**
     * Ref is the git ref the GitHub version was read from (e.g.
     * origin/release/1.0.x), or "werkmap" when the working tree was the only
     * available source.
     */
    "ref": string;

    /** Creates a new InventoryProjectRef instance. */
    constructor($$source: Partial<InventoryProjectRef> = {}) {
        if (!("projectId" in $$source)) {
            this["projectId"] = "";
        }
        if (!("projectName" in $$source)) {
            this["projectName"] = "";
        }
        if (!("localVersion" in $$source)) {
            this["localVersion"] = "";
        }
        if (!("githubVersion" in $$source)) {
            this["githubVersion"] = "";
        }
        if (!("outdated" in $$source)) {
            this["outdated"] = false;
        }
        if (!("localBehind" in $$source)) {
            this["localBehind"] = false;
        }
        if (!("ref" in $$source)) {
            this["ref"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InventoryProjectRef instance from a string or object.
     */
    static createFrom($$source: any = {}): InventoryProjectRef {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new InventoryProjectRef($$parsedSource as Partial<InventoryProjectRef>);
    }
}

/**
 * LocalApplyPlugin is het resultaat voor één plugin.
 */
export class LocalApplyPlugin {
    "slug": string;
    "from": string;
    "to": string;

    /**
     * updated | error
     */
    "status": string;
    "error"?: string;

    /** Creates a new LocalApplyPlugin instance. */
    constructor($$source: Partial<LocalApplyPlugin> = {}) {
        if (!("slug" in $$source)) {
            this["slug"] = "";
        }
        if (!("from" in $$source)) {
            this["from"] = "";
        }
        if (!("to" in $$source)) {
            this["to"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LocalApplyPlugin instance from a string or object.
     */
    static createFrom($$source: any = {}): LocalApplyPlugin {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LocalApplyPlugin($$parsedSource as Partial<LocalApplyPlugin>);
    }
}

/**
 * LocalApplyResult is het resultaat van één plaatsing.
 */
export class LocalApplyResult {
    "branch": string;
    "plugins": LocalApplyPlugin[];

    /** Creates a new LocalApplyResult instance. */
    constructor($$source: Partial<LocalApplyResult> = {}) {
        if (!("branch" in $$source)) {
            this["branch"] = "";
        }
        if (!("plugins" in $$source)) {
            this["plugins"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LocalApplyResult instance from a string or object.
     */
    static createFrom($$source: any = {}): LocalApplyResult {
        const $$createField1_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("plugins" in $$parsedSource) {
            $$parsedSource["plugins"] = $$createField1_0($$parsedSource["plugins"]);
        }
        return new LocalApplyResult($$parsedSource as Partial<LocalApplyResult>);
    }
}

/**
 * LocalPaidPlugin is één zip uit de lokale map. Een onleesbare zip krijgt een
 * Error in plaats van dat hij stil verdwijnt — een typefout in een download wil je
 * zien, niet raden.
 */
export class LocalPaidPlugin {
    "slug": string;
    "version": string;
    "fileName": string;
    "isDir": boolean;
    "modifiedAt": number;
    "error"?: string;

    /** Creates a new LocalPaidPlugin instance. */
    constructor($$source: Partial<LocalPaidPlugin> = {}) {
        if (!("slug" in $$source)) {
            this["slug"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("fileName" in $$source)) {
            this["fileName"] = "";
        }
        if (!("isDir" in $$source)) {
            this["isDir"] = false;
        }
        if (!("modifiedAt" in $$source)) {
            this["modifiedAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LocalPaidPlugin instance from a string or object.
     */
    static createFrom($$source: any = {}): LocalPaidPlugin {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LocalPaidPlugin($$parsedSource as Partial<LocalPaidPlugin>);
    }
}

/**
 * LocalPluginOverview is wat de Plugins-tab nodig heeft: de rijen plus de branch
 * waarop een commit terecht zou komen. Die branch tonen is geen detail — de commit
 * gaat op de huidige checkout, dus de gebruiker moet zien welke dat is.
 */
export class LocalPluginOverview {
    "branch": string;
    "rows": LocalPluginRow[];

    /** Creates a new LocalPluginOverview instance. */
    constructor($$source: Partial<LocalPluginOverview> = {}) {
        if (!("branch" in $$source)) {
            this["branch"] = "";
        }
        if (!("rows" in $$source)) {
            this["rows"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LocalPluginOverview instance from a string or object.
     */
    static createFrom($$source: any = {}): LocalPluginOverview {
        const $$createField1_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("rows" in $$parsedSource) {
            $$parsedSource["rows"] = $$createField1_0($$parsedSource["rows"]);
        }
        return new LocalPluginOverview($$parsedSource as Partial<LocalPluginOverview>);
    }
}

/**
 * LocalPluginRow is de vergelijking van één zip met wat er in het project staat.
 */
export class LocalPluginRow {
    "slug": string;
    "fileName": string;
    "folderVersion": string;

    /**
     * leeg = niet in dit project
     */
    "projectVersion": string;
    "newer": boolean;

    /**
     * Error maakt een onbruikbare bron zichtbaar in het paneel zelf; een regel die
     * stil wegvalt leest als "de tool ziet mijn map niet".
     */
    "error"?: string;

    /** Creates a new LocalPluginRow instance. */
    constructor($$source: Partial<LocalPluginRow> = {}) {
        if (!("slug" in $$source)) {
            this["slug"] = "";
        }
        if (!("fileName" in $$source)) {
            this["fileName"] = "";
        }
        if (!("folderVersion" in $$source)) {
            this["folderVersion"] = "";
        }
        if (!("projectVersion" in $$source)) {
            this["projectVersion"] = "";
        }
        if (!("newer" in $$source)) {
            this["newer"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LocalPluginRow instance from a string or object.
     */
    static createFrom($$source: any = {}): LocalPluginRow {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LocalPluginRow($$parsedSource as Partial<LocalPluginRow>);
    }
}

/**
 * MakeResult holds the stdout/stderr output of a make invocation.
 */
export class MakeResult {
    "target": string;
    "output": string;
    "success": boolean;

    /** Creates a new MakeResult instance. */
    constructor($$source: Partial<MakeResult> = {}) {
        if (!("target" in $$source)) {
            this["target"] = "";
        }
        if (!("output" in $$source)) {
            this["output"] = "";
        }
        if (!("success" in $$source)) {
            this["success"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MakeResult instance from a string or object.
     */
    static createFrom($$source: any = {}): MakeResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MakeResult($$parsedSource as Partial<MakeResult>);
    }
}

/**
 * MakeTarget is a parsed Makefile target.
 */
export class MakeTarget {
    "name": string;

    /** Creates a new MakeTarget instance. */
    constructor($$source: Partial<MakeTarget> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MakeTarget instance from a string or object.
     */
    static createFrom($$source: any = {}): MakeTarget {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MakeTarget($$parsedSource as Partial<MakeTarget>);
    }
}

/**
 * MediaCrawlConflict is een bestand waarover de twee methodes het oneens zijn: de
 * databasescan vond geen enkele verwijzing, maar de browser vroeg het wél op. Dat is
 * geen foutmelding maar een controlelijst — elke regel is met één klik na te lopen.
 */
export class MediaCrawlConflict {
    "path": string;
    "bytes": number;
    "modifiedAt": number;
    "attachmentId"?: number;
    "title"?: string;
    "pages": string[];

    /** Creates a new MediaCrawlConflict instance. */
    constructor($$source: Partial<MediaCrawlConflict> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("bytes" in $$source)) {
            this["bytes"] = 0;
        }
        if (!("modifiedAt" in $$source)) {
            this["modifiedAt"] = 0;
        }
        if (!("pages" in $$source)) {
            this["pages"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MediaCrawlConflict instance from a string or object.
     */
    static createFrom($$source: any = {}): MediaCrawlConflict {
        const $$createField5_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("pages" in $$parsedSource) {
            $$parsedSource["pages"] = $$createField5_0($$parsedSource["pages"]);
        }
        return new MediaCrawlConflict($$parsedSource as Partial<MediaCrawlConflict>);
    }
}

/**
 * MediaCrawlResult is what a rendered crawl established. The counts are the point:
 * they say how much of the "no reference found" list is actually served to visitors,
 * which is the one check a database scan cannot perform.
 */
export class MediaCrawlResult {
    "scanId": string;
    "siteUrl": string;
    "crawledAt": string;
    "pagesVisited": number;
    "pagesPlanned": number;
    "uploadsSeen": number;
    "unreferencedSeen": number;
    "errors": string[];
    "pages"?: { [_ in string]?: string[] };

    /** Creates a new MediaCrawlResult instance. */
    constructor($$source: Partial<MediaCrawlResult> = {}) {
        if (!("scanId" in $$source)) {
            this["scanId"] = "";
        }
        if (!("siteUrl" in $$source)) {
            this["siteUrl"] = "";
        }
        if (!("crawledAt" in $$source)) {
            this["crawledAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("pagesVisited" in $$source)) {
            this["pagesVisited"] = 0;
        }
        if (!("pagesPlanned" in $$source)) {
            this["pagesPlanned"] = 0;
        }
        if (!("uploadsSeen" in $$source)) {
            this["uploadsSeen"] = 0;
        }
        if (!("unreferencedSeen" in $$source)) {
            this["unreferencedSeen"] = 0;
        }
        if (!("errors" in $$source)) {
            this["errors"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MediaCrawlResult instance from a string or object.
     */
    static createFrom($$source: any = {}): MediaCrawlResult {
        const $$createField7_0 = $$createType0;
        const $$createField8_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("errors" in $$parsedSource) {
            $$parsedSource["errors"] = $$createField7_0($$parsedSource["errors"]);
        }
        if ("pages" in $$parsedSource) {
            $$parsedSource["pages"] = $$createField8_0($$parsedSource["pages"]);
        }
        return new MediaCrawlResult($$parsedSource as Partial<MediaCrawlResult>);
    }
}

/**
 * MediaProbe is the outcome of a connection check against one environment.
 */
export class MediaProbe {
    "user": string;
    "home": string;
    "webroot": string;
    "wpCli": string;
    "uploadsKb": number;

    /** Creates a new MediaProbe instance. */
    constructor($$source: Partial<MediaProbe> = {}) {
        if (!("user" in $$source)) {
            this["user"] = "";
        }
        if (!("home" in $$source)) {
            this["home"] = "";
        }
        if (!("webroot" in $$source)) {
            this["webroot"] = "";
        }
        if (!("wpCli" in $$source)) {
            this["wpCli"] = "";
        }
        if (!("uploadsKb" in $$source)) {
            this["uploadsKb"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MediaProbe instance from a string or object.
     */
    static createFrom($$source: any = {}): MediaProbe {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MediaProbe($$parsedSource as Partial<MediaProbe>);
    }
}

/**
 * PackageUpdate is a single package version change (or availability).
 */
export class PackageUpdate {
    "name": string;
    "from": string;
    "to": string;

    /**
     * "minor" | "patch" (npm applied)
     */
    "type"?: string;

    /**
     * "applied" | "manual" | "" (onbekend)
     */
    "status"?: string;

    /**
     * toelichting bij "manual"
     */
    "reason"?: string;

    /** Creates a new PackageUpdate instance. */
    constructor($$source: Partial<PackageUpdate> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("from" in $$source)) {
            this["from"] = "";
        }
        if (!("to" in $$source)) {
            this["to"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PackageUpdate instance from a string or object.
     */
    static createFrom($$source: any = {}): PackageUpdate {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PackageUpdate($$parsedSource as Partial<PackageUpdate>);
    }
}

export class PluginUpdateResult {
    "slug": string;
    "from": string;
    "to": string;

    /**
     * updated | manual | error
     */
    "status": string;
    "error": string;

    /** Creates a new PluginUpdateResult instance. */
    constructor($$source: Partial<PluginUpdateResult> = {}) {
        if (!("slug" in $$source)) {
            this["slug"] = "";
        }
        if (!("from" in $$source)) {
            this["from"] = "";
        }
        if (!("to" in $$source)) {
            this["to"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PluginUpdateResult instance from a string or object.
     */
    static createFrom($$source: any = {}): PluginUpdateResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PluginUpdateResult($$parsedSource as Partial<PluginUpdateResult>);
    }
}

export class ProjectUpdateResult {
    "projectId": string;
    "projectName": string;

    /**
     * updated | needs_stash | skipped_no_release | error | nothing
     */
    "status": string;
    "branch": string;
    "error": string;
    "plugins": PluginUpdateResult[];

    /**
     * Stashed is true when ApplyProject performed an auto-stash of local
     * changes before proceeding. Surfaced so the user knows their WIP was
     * stashed even if the run ends in "updated", "nothing", or "error".
     */
    "stashed": boolean;

    /** Creates a new ProjectUpdateResult instance. */
    constructor($$source: Partial<ProjectUpdateResult> = {}) {
        if (!("projectId" in $$source)) {
            this["projectId"] = "";
        }
        if (!("projectName" in $$source)) {
            this["projectName"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("branch" in $$source)) {
            this["branch"] = "";
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }
        if (!("plugins" in $$source)) {
            this["plugins"] = [];
        }
        if (!("stashed" in $$source)) {
            this["stashed"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProjectUpdateResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ProjectUpdateResult {
        const $$createField5_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("plugins" in $$parsedSource) {
            $$parsedSource["plugins"] = $$createField5_0($$parsedSource["plugins"]);
        }
        return new ProjectUpdateResult($$parsedSource as Partial<ProjectUpdateResult>);
    }
}

export class ProjectVulnReport {
    "projectId": string;
    "projectName": string;
    "path": string;
    "findings": WordfenceVulnFinding[];
    "skipped": boolean;
    "skipReason": string;

    /** Creates a new ProjectVulnReport instance. */
    constructor($$source: Partial<ProjectVulnReport> = {}) {
        if (!("projectId" in $$source)) {
            this["projectId"] = "";
        }
        if (!("projectName" in $$source)) {
            this["projectName"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("findings" in $$source)) {
            this["findings"] = [];
        }
        if (!("skipped" in $$source)) {
            this["skipped"] = false;
        }
        if (!("skipReason" in $$source)) {
            this["skipReason"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProjectVulnReport instance from a string or object.
     */
    static createFrom($$source: any = {}): ProjectVulnReport {
        const $$createField3_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("findings" in $$parsedSource) {
            $$parsedSource["findings"] = $$createField3_0($$parsedSource["findings"]);
        }
        return new ProjectVulnReport($$parsedSource as Partial<ProjectVulnReport>);
    }
}

/**
 * ProjectWorkflow is een actieve GitHub Actions workflow van een project-repo,
 * met de status van de meest recente run.
 */
export class ProjectWorkflow {
    "id": number;
    "name": string;
    "path": string;
    "runStatus": string;
    "runConclusion": string;
    "runUrl": string;
    "runAt": string;

    /** Creates a new ProjectWorkflow instance. */
    constructor($$source: Partial<ProjectWorkflow> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("runStatus" in $$source)) {
            this["runStatus"] = "";
        }
        if (!("runConclusion" in $$source)) {
            this["runConclusion"] = "";
        }
        if (!("runUrl" in $$source)) {
            this["runUrl"] = "";
        }
        if (!("runAt" in $$source)) {
            this["runAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProjectWorkflow instance from a string or object.
     */
    static createFrom($$source: any = {}): ProjectWorkflow {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProjectWorkflow($$parsedSource as Partial<ProjectWorkflow>);
    }
}

/**
 * QuarantineBatch is one set of moved files, as recorded on the server.
 */
export class QuarantineBatch {
    "batch": string;
    "created": string;
    "files": number;
    "bytes": number;

    /** Creates a new QuarantineBatch instance. */
    constructor($$source: Partial<QuarantineBatch> = {}) {
        if (!("batch" in $$source)) {
            this["batch"] = "";
        }
        if (!("created" in $$source)) {
            this["created"] = "";
        }
        if (!("files" in $$source)) {
            this["files"] = 0;
        }
        if (!("bytes" in $$source)) {
            this["bytes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QuarantineBatch instance from a string or object.
     */
    static createFrom($$source: any = {}): QuarantineBatch {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new QuarantineBatch($$parsedSource as Partial<QuarantineBatch>);
    }
}

/**
 * QuarantineEntry is one moved file.
 */
export class QuarantineEntry {
    "original": string;
    "stored": string;
    "bytes": number;

    /** Creates a new QuarantineEntry instance. */
    constructor($$source: Partial<QuarantineEntry> = {}) {
        if (!("original" in $$source)) {
            this["original"] = "";
        }
        if (!("stored" in $$source)) {
            this["stored"] = "";
        }
        if (!("bytes" in $$source)) {
            this["bytes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QuarantineEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): QuarantineEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new QuarantineEntry($$parsedSource as Partial<QuarantineEntry>);
    }
}

/**
 * QuarantineResult is the outcome of a move or restore.
 */
export class QuarantineResult {
    "batch": string;
    "moved": QuarantineEntry[];
    "skipped": QuarantineSkip[];
    "bytes": number;
    "quarantineDir": string;
    "batches": QuarantineBatch[];
    "error": string;

    /** Creates a new QuarantineResult instance. */
    constructor($$source: Partial<QuarantineResult> = {}) {
        if (!("batch" in $$source)) {
            this["batch"] = "";
        }
        if (!("moved" in $$source)) {
            this["moved"] = [];
        }
        if (!("skipped" in $$source)) {
            this["skipped"] = [];
        }
        if (!("bytes" in $$source)) {
            this["bytes"] = 0;
        }
        if (!("quarantineDir" in $$source)) {
            this["quarantineDir"] = "";
        }
        if (!("batches" in $$source)) {
            this["batches"] = [];
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QuarantineResult instance from a string or object.
     */
    static createFrom($$source: any = {}): QuarantineResult {
        const $$createField1_0 = $$createType13;
        const $$createField2_0 = $$createType15;
        const $$createField5_0 = $$createType17;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("moved" in $$parsedSource) {
            $$parsedSource["moved"] = $$createField1_0($$parsedSource["moved"]);
        }
        if ("skipped" in $$parsedSource) {
            $$parsedSource["skipped"] = $$createField2_0($$parsedSource["skipped"]);
        }
        if ("batches" in $$parsedSource) {
            $$parsedSource["batches"] = $$createField5_0($$parsedSource["batches"]);
        }
        return new QuarantineResult($$parsedSource as Partial<QuarantineResult>);
    }
}

/**
 * QuarantineSkip is one file that was left alone, with the reason.
 */
export class QuarantineSkip {
    "path": string;
    "reason": string;

    /** Creates a new QuarantineSkip instance. */
    constructor($$source: Partial<QuarantineSkip> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("reason" in $$source)) {
            this["reason"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QuarantineSkip instance from a string or object.
     */
    static createFrom($$source: any = {}): QuarantineSkip {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new QuarantineSkip($$parsedSource as Partial<QuarantineSkip>);
    }
}

/**
 * SSHAccess is what a project knows about reaching its own server. Kinsta's API
 * supplies none of this, so it is entered once and then remembered. The password
 * itself never leaves the keychain — only whether there is one.
 */
export class SSHAccess {
    "user": string;
    "path": string;
    "hasPassword": boolean;

    /** Creates a new SSHAccess instance. */
    constructor($$source: Partial<SSHAccess> = {}) {
        if (!("user" in $$source)) {
            this["user"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("hasPassword" in $$source)) {
            this["hasPassword"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SSHAccess instance from a string or object.
     */
    static createFrom($$source: any = {}): SSHAccess {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SSHAccess($$parsedSource as Partial<SSHAccess>);
    }
}

/**
 * SearchHit represents a single grep match in a file.
 */
export class SearchHit {
    "projectId": string;
    "displayName": string;
    "file": string;
    "line": number;
    "content": string;

    /** Creates a new SearchHit instance. */
    constructor($$source: Partial<SearchHit> = {}) {
        if (!("projectId" in $$source)) {
            this["projectId"] = "";
        }
        if (!("displayName" in $$source)) {
            this["displayName"] = "";
        }
        if (!("file" in $$source)) {
            this["file"] = "";
        }
        if (!("line" in $$source)) {
            this["line"] = 0;
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchHit instance from a string or object.
     */
    static createFrom($$source: any = {}): SearchHit {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SearchHit($$parsedSource as Partial<SearchHit>);
    }
}

/**
 * SecurityFinding is één kwetsbaarheid uit een composer- of npm-audit.
 */
export class SecurityFinding {
    /**
     * "composer" | "npm"
     */
    "source": string;

    /**
     * pakketnaam
     */
    "package": string;

    /**
     * critical | high | moderate/medium | low | unknown
     */
    "severity": string;
    "title": string;
    "cve": string;
    "link": string;

    /** Creates a new SecurityFinding instance. */
    constructor($$source: Partial<SecurityFinding> = {}) {
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("package" in $$source)) {
            this["package"] = "";
        }
        if (!("severity" in $$source)) {
            this["severity"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("cve" in $$source)) {
            this["cve"] = "";
        }
        if (!("link" in $$source)) {
            this["link"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SecurityFinding instance from a string or object.
     */
    static createFrom($$source: any = {}): SecurityFinding {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SecurityFinding($$parsedSource as Partial<SecurityFinding>);
    }
}

/**
 * SecurityScanResult is de meest recente scan-uitkomst van een project-repo.
 */
export class SecurityScanResult {
    "repo": string;
    "scannedAt": string;
    "hasComposerReport": boolean;
    "hasNpmReport": boolean;
    "findings": SecurityFinding[];

    /** Creates a new SecurityScanResult instance. */
    constructor($$source: Partial<SecurityScanResult> = {}) {
        if (!("repo" in $$source)) {
            this["repo"] = "";
        }
        if (!("scannedAt" in $$source)) {
            this["scannedAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("hasComposerReport" in $$source)) {
            this["hasComposerReport"] = false;
        }
        if (!("hasNpmReport" in $$source)) {
            this["hasNpmReport"] = false;
        }
        if (!("findings" in $$source)) {
            this["findings"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SecurityScanResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SecurityScanResult {
        const $$createField4_0 = $$createType19;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("findings" in $$parsedSource) {
            $$parsedSource["findings"] = $$createField4_0($$parsedSource["findings"]);
        }
        return new SecurityScanResult($$parsedSource as Partial<SecurityScanResult>);
    }
}

/**
 * SiteLinkConflict reports a Kinsta site that is linked to more than one project.
 */
export class SiteLinkConflict {
    "siteId": string;
    "projects": string[];

    /** Creates a new SiteLinkConflict instance. */
    constructor($$source: Partial<SiteLinkConflict> = {}) {
        if (!("siteId" in $$source)) {
            this["siteId"] = "";
        }
        if (!("projects" in $$source)) {
            this["projects"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SiteLinkConflict instance from a string or object.
     */
    static createFrom($$source: any = {}): SiteLinkConflict {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("projects" in $$parsedSource) {
            $$parsedSource["projects"] = $$createField1_0($$parsedSource["projects"]);
        }
        return new SiteLinkConflict($$parsedSource as Partial<SiteLinkConflict>);
    }
}

/**
 * GetFiles returns all tracked files in the repository via git ls-files.
 * UpdateBranch represents a detected automated WordPress update branch.
 */
export class UpdateBranch {
    "name": string;

    /**
     * without remote prefix
     */
    "shortName": string;

    /**
     * raw date portion from branch name
     */
    "dateStr": string;

    /**
     * true if also checked out locally
     */
    "isLocal": boolean;

    /** Creates a new UpdateBranch instance. */
    constructor($$source: Partial<UpdateBranch> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("shortName" in $$source)) {
            this["shortName"] = "";
        }
        if (!("dateStr" in $$source)) {
            this["dateStr"] = "";
        }
        if (!("isLocal" in $$source)) {
            this["isLocal"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateBranch instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateBranch {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateBranch($$parsedSource as Partial<UpdateBranch>);
    }
}

/**
 * UpdateDetail is the fully resolved set of updates inside an update branch.
 */
export class UpdateDetail {
    /**
     * "manifest" | "fallback"
     */
    "source": string;
    "generatedAt"?: string;
    "wpCore": WPCoreUpdate[];
    "wpPlugins": PackageUpdate[];
    "wpThemes": PackageUpdate[];
    "npmApplied": PackageUpdate[];
    "npmAvailableMajors": PackageUpdate[];

    /** Creates a new UpdateDetail instance. */
    constructor($$source: Partial<UpdateDetail> = {}) {
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("wpCore" in $$source)) {
            this["wpCore"] = [];
        }
        if (!("wpPlugins" in $$source)) {
            this["wpPlugins"] = [];
        }
        if (!("wpThemes" in $$source)) {
            this["wpThemes"] = [];
        }
        if (!("npmApplied" in $$source)) {
            this["npmApplied"] = [];
        }
        if (!("npmAvailableMajors" in $$source)) {
            this["npmAvailableMajors"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateDetail instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateDetail {
        const $$createField2_0 = $$createType21;
        const $$createField3_0 = $$createType23;
        const $$createField4_0 = $$createType23;
        const $$createField5_0 = $$createType23;
        const $$createField6_0 = $$createType23;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("wpCore" in $$parsedSource) {
            $$parsedSource["wpCore"] = $$createField2_0($$parsedSource["wpCore"]);
        }
        if ("wpPlugins" in $$parsedSource) {
            $$parsedSource["wpPlugins"] = $$createField3_0($$parsedSource["wpPlugins"]);
        }
        if ("wpThemes" in $$parsedSource) {
            $$parsedSource["wpThemes"] = $$createField4_0($$parsedSource["wpThemes"]);
        }
        if ("npmApplied" in $$parsedSource) {
            $$parsedSource["npmApplied"] = $$createField5_0($$parsedSource["npmApplied"]);
        }
        if ("npmAvailableMajors" in $$parsedSource) {
            $$parsedSource["npmAvailableMajors"] = $$createField6_0($$parsedSource["npmAvailableMajors"]);
        }
        return new UpdateDetail($$parsedSource as Partial<UpdateDetail>);
    }
}

export class UpdateSelection {
    "projectId": string;
    "slugs": string[];

    /** Creates a new UpdateSelection instance. */
    constructor($$source: Partial<UpdateSelection> = {}) {
        if (!("projectId" in $$source)) {
            this["projectId"] = "";
        }
        if (!("slugs" in $$source)) {
            this["slugs"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateSelection instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateSelection {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("slugs" in $$parsedSource) {
            $$parsedSource["slugs"] = $$createField1_0($$parsedSource["slugs"]);
        }
        return new UpdateSelection($$parsedSource as Partial<UpdateSelection>);
    }
}

/**
 * VulnFinding is a single vulnerable plugin discovered on a Kinsta environment.
 */
export class VulnFinding {
    "projectId": string;
    "projectName": string;
    "siteId": string;
    "envId": string;
    "envName": string;
    "slug": string;
    "version": string;

    /** Creates a new VulnFinding instance. */
    constructor($$source: Partial<VulnFinding> = {}) {
        if (!("projectId" in $$source)) {
            this["projectId"] = "";
        }
        if (!("projectName" in $$source)) {
            this["projectName"] = "";
        }
        if (!("siteId" in $$source)) {
            this["siteId"] = "";
        }
        if (!("envId" in $$source)) {
            this["envId"] = "";
        }
        if (!("envName" in $$source)) {
            this["envName"] = "";
        }
        if (!("slug" in $$source)) {
            this["slug"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VulnFinding instance from a string or object.
     */
    static createFrom($$source: any = {}): VulnFinding {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VulnFinding($$parsedSource as Partial<VulnFinding>);
    }
}

/**
 * WPCoreReport lists each project's WordPress core version.
 */
export class WPCoreReport {
    "latestVersion": string;
    "projects": InventoryProjectRef[];

    /** Creates a new WPCoreReport instance. */
    constructor($$source: Partial<WPCoreReport> = {}) {
        if (!("latestVersion" in $$source)) {
            this["latestVersion"] = "";
        }
        if (!("projects" in $$source)) {
            this["projects"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WPCoreReport instance from a string or object.
     */
    static createFrom($$source: any = {}): WPCoreReport {
        const $$createField1_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("projects" in $$parsedSource) {
            $$parsedSource["projects"] = $$createField1_0($$parsedSource["projects"]);
        }
        return new WPCoreReport($$parsedSource as Partial<WPCoreReport>);
    }
}

/**
 * WPCoreUpdate is a single WordPress core version availability.
 */
export class WPCoreUpdate {
    "version": string;

    /**
     * "minor" | "major"
     */
    "updateType": string;
    "status"?: string;
    "reason"?: string;

    /** Creates a new WPCoreUpdate instance. */
    constructor($$source: Partial<WPCoreUpdate> = {}) {
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("updateType" in $$source)) {
            this["updateType"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WPCoreUpdate instance from a string or object.
     */
    static createFrom($$source: any = {}): WPCoreUpdate {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WPCoreUpdate($$parsedSource as Partial<WPCoreUpdate>);
    }
}

/**
 * WordfenceVulnFinding is a single vulnerability match against an installed
 * plugin, produced by WordfenceService.MatchProjects. Named distinctly from
 * VulnFinding (vuln_scan_service.go, Kinsta-environment scan results) to
 * avoid a package-level identifier collision.
 */
export class WordfenceVulnFinding {
    "slug": string;
    "installedVersion": string;
    "latestVersion": string;

    /**
     * "wporg" | "manual"
     */
    "source": string;
    "cve": string;
    "severity": string;
    "title": string;
    "vulnId": string;

    /** Creates a new WordfenceVulnFinding instance. */
    constructor($$source: Partial<WordfenceVulnFinding> = {}) {
        if (!("slug" in $$source)) {
            this["slug"] = "";
        }
        if (!("installedVersion" in $$source)) {
            this["installedVersion"] = "";
        }
        if (!("latestVersion" in $$source)) {
            this["latestVersion"] = "";
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("cve" in $$source)) {
            this["cve"] = "";
        }
        if (!("severity" in $$source)) {
            this["severity"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("vulnId" in $$source)) {
            this["vulnId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WordfenceVulnFinding instance from a string or object.
     */
    static createFrom($$source: any = {}): WordfenceVulnFinding {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WordfenceVulnFinding($$parsedSource as Partial<WordfenceVulnFinding>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = InventoryProjectRef.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = LocalApplyPlugin.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = LocalPluginRow.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = $Create.Map($Create.Any, $$createType0);
const $$createType8 = PluginUpdateResult.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = WordfenceVulnFinding.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = QuarantineEntry.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = QuarantineSkip.createFrom;
const $$createType15 = $Create.Array($$createType14);
const $$createType16 = QuarantineBatch.createFrom;
const $$createType17 = $Create.Array($$createType16);
const $$createType18 = SecurityFinding.createFrom;
const $$createType19 = $Create.Array($$createType18);
const $$createType20 = WPCoreUpdate.createFrom;
const $$createType21 = $Create.Array($$createType20);
const $$createType22 = PackageUpdate.createFrom;
const $$createType23 = $Create.Array($$createType22);
