// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

/**
 * AppSettings is the flat DTO exposed to the frontend.
 */
export class AppSettings {
    "editor": string;
    "kinstaApiKey": string;
    "kinstaCompanyId": string;
    "githubToken": string;
    "pluginRepo": string;
    "pluginRepoRef": string;
    "gitDefaultRemote": string;
    "gitPruneOnFetch": boolean;
    "anthropicApiKey": string;
    "wordfenceApiKey": string;

    /** Creates a new AppSettings instance. */
    constructor($$source: Partial<AppSettings> = {}) {
        if (!("editor" in $$source)) {
            this["editor"] = "";
        }
        if (!("kinstaApiKey" in $$source)) {
            this["kinstaApiKey"] = "";
        }
        if (!("kinstaCompanyId" in $$source)) {
            this["kinstaCompanyId"] = "";
        }
        if (!("githubToken" in $$source)) {
            this["githubToken"] = "";
        }
        if (!("pluginRepo" in $$source)) {
            this["pluginRepo"] = "";
        }
        if (!("pluginRepoRef" in $$source)) {
            this["pluginRepoRef"] = "";
        }
        if (!("gitDefaultRemote" in $$source)) {
            this["gitDefaultRemote"] = "";
        }
        if (!("gitPruneOnFetch" in $$source)) {
            this["gitPruneOnFetch"] = false;
        }
        if (!("anthropicApiKey" in $$source)) {
            this["anthropicApiKey"] = "";
        }
        if (!("wordfenceApiKey" in $$source)) {
            this["wordfenceApiKey"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): AppSettings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppSettings($$parsedSource as Partial<AppSettings>);
    }
}

/**
 * BatchResult holds the outcome of a single project operation.
 */
export class BatchResult {
    "projectId": string;
    "displayName": string;
    "op": string;
    "success": boolean;
    "error"?: string;

    /** Creates a new BatchResult instance. */
    constructor($$source: Partial<BatchResult> = {}) {
        if (!("projectId" in $$source)) {
            this["projectId"] = "";
        }
        if (!("displayName" in $$source)) {
            this["displayName"] = "";
        }
        if (!("op" in $$source)) {
            this["op"] = "";
        }
        if (!("success" in $$source)) {
            this["success"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BatchResult instance from a string or object.
     */
    static createFrom($$source: any = {}): BatchResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BatchResult($$parsedSource as Partial<BatchResult>);
    }
}

export class FeedMeta {
    "fetchedAt": time$0.Time;
    "count": number;

    /** Creates a new FeedMeta instance. */
    constructor($$source: Partial<FeedMeta> = {}) {
        if (!("fetchedAt" in $$source)) {
            this["fetchedAt"] = null;
        }
        if (!("count" in $$source)) {
            this["count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FeedMeta instance from a string or object.
     */
    static createFrom($$source: any = {}): FeedMeta {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FeedMeta($$parsedSource as Partial<FeedMeta>);
    }
}

/**
 * MakeResult holds the stdout/stderr output of a make invocation.
 */
export class MakeResult {
    "target": string;
    "output": string;
    "success": boolean;

    /** Creates a new MakeResult instance. */
    constructor($$source: Partial<MakeResult> = {}) {
        if (!("target" in $$source)) {
            this["target"] = "";
        }
        if (!("output" in $$source)) {
            this["output"] = "";
        }
        if (!("success" in $$source)) {
            this["success"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MakeResult instance from a string or object.
     */
    static createFrom($$source: any = {}): MakeResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MakeResult($$parsedSource as Partial<MakeResult>);
    }
}

/**
 * MakeTarget is a parsed Makefile target.
 */
export class MakeTarget {
    "name": string;

    /** Creates a new MakeTarget instance. */
    constructor($$source: Partial<MakeTarget> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MakeTarget instance from a string or object.
     */
    static createFrom($$source: any = {}): MakeTarget {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MakeTarget($$parsedSource as Partial<MakeTarget>);
    }
}

/**
 * PackageUpdate is a single package version change (or availability).
 */
export class PackageUpdate {
    "name": string;
    "from": string;
    "to": string;

    /**
     * "minor" | "patch" (npm applied)
     */
    "type"?: string;

    /**
     * "applied" | "manual" | "" (onbekend)
     */
    "status"?: string;

    /**
     * toelichting bij "manual"
     */
    "reason"?: string;

    /** Creates a new PackageUpdate instance. */
    constructor($$source: Partial<PackageUpdate> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("from" in $$source)) {
            this["from"] = "";
        }
        if (!("to" in $$source)) {
            this["to"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PackageUpdate instance from a string or object.
     */
    static createFrom($$source: any = {}): PackageUpdate {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PackageUpdate($$parsedSource as Partial<PackageUpdate>);
    }
}

export class PluginUpdateResult {
    "slug": string;
    "from": string;
    "to": string;

    /**
     * updated | manual | error
     */
    "status": string;
    "error": string;

    /** Creates a new PluginUpdateResult instance. */
    constructor($$source: Partial<PluginUpdateResult> = {}) {
        if (!("slug" in $$source)) {
            this["slug"] = "";
        }
        if (!("from" in $$source)) {
            this["from"] = "";
        }
        if (!("to" in $$source)) {
            this["to"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PluginUpdateResult instance from a string or object.
     */
    static createFrom($$source: any = {}): PluginUpdateResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PluginUpdateResult($$parsedSource as Partial<PluginUpdateResult>);
    }
}

export class ProjectUpdateResult {
    "projectId": string;
    "projectName": string;

    /**
     * updated | needs_stash | skipped_no_release | error | nothing
     */
    "status": string;
    "branch": string;
    "error": string;
    "plugins": PluginUpdateResult[];

    /**
     * Stashed is true when ApplyProject performed an auto-stash of local
     * changes before proceeding. Surfaced so the user knows their WIP was
     * stashed even if the run ends in "updated", "nothing", or "error".
     */
    "stashed": boolean;

    /** Creates a new ProjectUpdateResult instance. */
    constructor($$source: Partial<ProjectUpdateResult> = {}) {
        if (!("projectId" in $$source)) {
            this["projectId"] = "";
        }
        if (!("projectName" in $$source)) {
            this["projectName"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("branch" in $$source)) {
            this["branch"] = "";
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }
        if (!("plugins" in $$source)) {
            this["plugins"] = [];
        }
        if (!("stashed" in $$source)) {
            this["stashed"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProjectUpdateResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ProjectUpdateResult {
        const $$createField5_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("plugins" in $$parsedSource) {
            $$parsedSource["plugins"] = $$createField5_0($$parsedSource["plugins"]);
        }
        return new ProjectUpdateResult($$parsedSource as Partial<ProjectUpdateResult>);
    }
}

export class ProjectVulnReport {
    "projectId": string;
    "projectName": string;
    "path": string;
    "findings": WordfenceVulnFinding[];
    "skipped": boolean;
    "skipReason": string;

    /** Creates a new ProjectVulnReport instance. */
    constructor($$source: Partial<ProjectVulnReport> = {}) {
        if (!("projectId" in $$source)) {
            this["projectId"] = "";
        }
        if (!("projectName" in $$source)) {
            this["projectName"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("findings" in $$source)) {
            this["findings"] = [];
        }
        if (!("skipped" in $$source)) {
            this["skipped"] = false;
        }
        if (!("skipReason" in $$source)) {
            this["skipReason"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProjectVulnReport instance from a string or object.
     */
    static createFrom($$source: any = {}): ProjectVulnReport {
        const $$createField3_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("findings" in $$parsedSource) {
            $$parsedSource["findings"] = $$createField3_0($$parsedSource["findings"]);
        }
        return new ProjectVulnReport($$parsedSource as Partial<ProjectVulnReport>);
    }
}

/**
 * ProjectWorkflow is een actieve GitHub Actions workflow van een project-repo,
 * met de status van de meest recente run.
 */
export class ProjectWorkflow {
    "id": number;
    "name": string;
    "path": string;
    "runStatus": string;
    "runConclusion": string;
    "runUrl": string;
    "runAt": string;

    /** Creates a new ProjectWorkflow instance. */
    constructor($$source: Partial<ProjectWorkflow> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("runStatus" in $$source)) {
            this["runStatus"] = "";
        }
        if (!("runConclusion" in $$source)) {
            this["runConclusion"] = "";
        }
        if (!("runUrl" in $$source)) {
            this["runUrl"] = "";
        }
        if (!("runAt" in $$source)) {
            this["runAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProjectWorkflow instance from a string or object.
     */
    static createFrom($$source: any = {}): ProjectWorkflow {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProjectWorkflow($$parsedSource as Partial<ProjectWorkflow>);
    }
}

/**
 * SearchHit represents a single grep match in a file.
 */
export class SearchHit {
    "projectId": string;
    "displayName": string;
    "file": string;
    "line": number;
    "content": string;

    /** Creates a new SearchHit instance. */
    constructor($$source: Partial<SearchHit> = {}) {
        if (!("projectId" in $$source)) {
            this["projectId"] = "";
        }
        if (!("displayName" in $$source)) {
            this["displayName"] = "";
        }
        if (!("file" in $$source)) {
            this["file"] = "";
        }
        if (!("line" in $$source)) {
            this["line"] = 0;
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchHit instance from a string or object.
     */
    static createFrom($$source: any = {}): SearchHit {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SearchHit($$parsedSource as Partial<SearchHit>);
    }
}

/**
 * SecurityFinding is één kwetsbaarheid uit een composer- of npm-audit.
 */
export class SecurityFinding {
    /**
     * "composer" | "npm"
     */
    "source": string;

    /**
     * pakketnaam
     */
    "package": string;

    /**
     * critical | high | moderate/medium | low | unknown
     */
    "severity": string;
    "title": string;
    "cve": string;
    "link": string;

    /** Creates a new SecurityFinding instance. */
    constructor($$source: Partial<SecurityFinding> = {}) {
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("package" in $$source)) {
            this["package"] = "";
        }
        if (!("severity" in $$source)) {
            this["severity"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("cve" in $$source)) {
            this["cve"] = "";
        }
        if (!("link" in $$source)) {
            this["link"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SecurityFinding instance from a string or object.
     */
    static createFrom($$source: any = {}): SecurityFinding {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SecurityFinding($$parsedSource as Partial<SecurityFinding>);
    }
}

/**
 * SecurityScanResult is de meest recente scan-uitkomst van een project-repo.
 */
export class SecurityScanResult {
    "repo": string;
    "scannedAt": time$0.Time;
    "hasComposerReport": boolean;
    "hasNpmReport": boolean;
    "findings": SecurityFinding[];

    /** Creates a new SecurityScanResult instance. */
    constructor($$source: Partial<SecurityScanResult> = {}) {
        if (!("repo" in $$source)) {
            this["repo"] = "";
        }
        if (!("scannedAt" in $$source)) {
            this["scannedAt"] = null;
        }
        if (!("hasComposerReport" in $$source)) {
            this["hasComposerReport"] = false;
        }
        if (!("hasNpmReport" in $$source)) {
            this["hasNpmReport"] = false;
        }
        if (!("findings" in $$source)) {
            this["findings"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SecurityScanResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SecurityScanResult {
        const $$createField4_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("findings" in $$parsedSource) {
            $$parsedSource["findings"] = $$createField4_0($$parsedSource["findings"]);
        }
        return new SecurityScanResult($$parsedSource as Partial<SecurityScanResult>);
    }
}

/**
 * GetFiles returns all tracked files in the repository via git ls-files.
 * UpdateBranch represents a detected automated WordPress update branch.
 */
export class UpdateBranch {
    "name": string;

    /**
     * without remote prefix
     */
    "shortName": string;

    /**
     * raw date portion from branch name
     */
    "dateStr": string;

    /**
     * true if also checked out locally
     */
    "isLocal": boolean;

    /** Creates a new UpdateBranch instance. */
    constructor($$source: Partial<UpdateBranch> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("shortName" in $$source)) {
            this["shortName"] = "";
        }
        if (!("dateStr" in $$source)) {
            this["dateStr"] = "";
        }
        if (!("isLocal" in $$source)) {
            this["isLocal"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateBranch instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateBranch {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateBranch($$parsedSource as Partial<UpdateBranch>);
    }
}

/**
 * UpdateDetail is the fully resolved set of updates inside an update branch.
 */
export class UpdateDetail {
    /**
     * "manifest" | "fallback"
     */
    "source": string;
    "generatedAt"?: string;
    "wpCore": WPCoreUpdate[];
    "wpPlugins": PackageUpdate[];
    "wpThemes": PackageUpdate[];
    "npmApplied": PackageUpdate[];
    "npmAvailableMajors": PackageUpdate[];

    /** Creates a new UpdateDetail instance. */
    constructor($$source: Partial<UpdateDetail> = {}) {
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("wpCore" in $$source)) {
            this["wpCore"] = [];
        }
        if (!("wpPlugins" in $$source)) {
            this["wpPlugins"] = [];
        }
        if (!("wpThemes" in $$source)) {
            this["wpThemes"] = [];
        }
        if (!("npmApplied" in $$source)) {
            this["npmApplied"] = [];
        }
        if (!("npmAvailableMajors" in $$source)) {
            this["npmAvailableMajors"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateDetail instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateDetail {
        const $$createField2_0 = $$createType7;
        const $$createField3_0 = $$createType9;
        const $$createField4_0 = $$createType9;
        const $$createField5_0 = $$createType9;
        const $$createField6_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("wpCore" in $$parsedSource) {
            $$parsedSource["wpCore"] = $$createField2_0($$parsedSource["wpCore"]);
        }
        if ("wpPlugins" in $$parsedSource) {
            $$parsedSource["wpPlugins"] = $$createField3_0($$parsedSource["wpPlugins"]);
        }
        if ("wpThemes" in $$parsedSource) {
            $$parsedSource["wpThemes"] = $$createField4_0($$parsedSource["wpThemes"]);
        }
        if ("npmApplied" in $$parsedSource) {
            $$parsedSource["npmApplied"] = $$createField5_0($$parsedSource["npmApplied"]);
        }
        if ("npmAvailableMajors" in $$parsedSource) {
            $$parsedSource["npmAvailableMajors"] = $$createField6_0($$parsedSource["npmAvailableMajors"]);
        }
        return new UpdateDetail($$parsedSource as Partial<UpdateDetail>);
    }
}

export class UpdateSelection {
    "projectId": string;
    "slugs": string[];

    /** Creates a new UpdateSelection instance. */
    constructor($$source: Partial<UpdateSelection> = {}) {
        if (!("projectId" in $$source)) {
            this["projectId"] = "";
        }
        if (!("slugs" in $$source)) {
            this["slugs"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateSelection instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateSelection {
        const $$createField1_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("slugs" in $$parsedSource) {
            $$parsedSource["slugs"] = $$createField1_0($$parsedSource["slugs"]);
        }
        return new UpdateSelection($$parsedSource as Partial<UpdateSelection>);
    }
}

/**
 * VulnFinding is a single vulnerable plugin discovered on a Kinsta environment.
 */
export class VulnFinding {
    "projectId": string;
    "projectName": string;
    "siteId": string;
    "envId": string;
    "envName": string;
    "slug": string;
    "version": string;

    /** Creates a new VulnFinding instance. */
    constructor($$source: Partial<VulnFinding> = {}) {
        if (!("projectId" in $$source)) {
            this["projectId"] = "";
        }
        if (!("projectName" in $$source)) {
            this["projectName"] = "";
        }
        if (!("siteId" in $$source)) {
            this["siteId"] = "";
        }
        if (!("envId" in $$source)) {
            this["envId"] = "";
        }
        if (!("envName" in $$source)) {
            this["envName"] = "";
        }
        if (!("slug" in $$source)) {
            this["slug"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VulnFinding instance from a string or object.
     */
    static createFrom($$source: any = {}): VulnFinding {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VulnFinding($$parsedSource as Partial<VulnFinding>);
    }
}

/**
 * WPCoreUpdate is a single WordPress core version availability.
 */
export class WPCoreUpdate {
    "version": string;

    /**
     * "minor" | "major"
     */
    "updateType": string;
    "status"?: string;
    "reason"?: string;

    /** Creates a new WPCoreUpdate instance. */
    constructor($$source: Partial<WPCoreUpdate> = {}) {
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("updateType" in $$source)) {
            this["updateType"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WPCoreUpdate instance from a string or object.
     */
    static createFrom($$source: any = {}): WPCoreUpdate {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WPCoreUpdate($$parsedSource as Partial<WPCoreUpdate>);
    }
}

/**
 * WordfenceVulnFinding is a single vulnerability match against an installed
 * plugin, produced by WordfenceService.MatchProjects. Named distinctly from
 * VulnFinding (vuln_scan_service.go, Kinsta-environment scan results) to
 * avoid a package-level identifier collision.
 */
export class WordfenceVulnFinding {
    "slug": string;
    "installedVersion": string;
    "latestVersion": string;

    /**
     * "wporg" | "manual"
     */
    "source": string;
    "cve": string;
    "severity": string;
    "title": string;
    "vulnId": string;

    /** Creates a new WordfenceVulnFinding instance. */
    constructor($$source: Partial<WordfenceVulnFinding> = {}) {
        if (!("slug" in $$source)) {
            this["slug"] = "";
        }
        if (!("installedVersion" in $$source)) {
            this["installedVersion"] = "";
        }
        if (!("latestVersion" in $$source)) {
            this["latestVersion"] = "";
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("cve" in $$source)) {
            this["cve"] = "";
        }
        if (!("severity" in $$source)) {
            this["severity"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("vulnId" in $$source)) {
            this["vulnId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WordfenceVulnFinding instance from a string or object.
     */
    static createFrom($$source: any = {}): WordfenceVulnFinding {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WordfenceVulnFinding($$parsedSource as Partial<WordfenceVulnFinding>);
    }
}

// Private type creation functions
const $$createType0 = PluginUpdateResult.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = WordfenceVulnFinding.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = SecurityFinding.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = WPCoreUpdate.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = PackageUpdate.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = $Create.Array($Create.Any);
