// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * Send sends a macOS notification via osascript.
 * @param {string} title
 * @param {string} message
 * @returns {$CancellablePromise<void>}
 */
export function Send(title, message) {
    return $Call.ByID(2045041654, title, message);
}
