// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * OrgSyncService haalt de repolijst van de GitHub-organisatie op, classificeert
 * elke repo via deploy_conf.json, en matcht het resultaat tegen de lokale
 * checkouts zodat direct zichtbaar is welke WordPress-sites nog geen lokale
 * map hebben.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../domain/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../wailsapp/wails/v3/pkg/application/models.js";

/**
 * Clone haalt de opgegeven org-repo's lokaal binnen in de eerste
 * geconfigureerde projects-root, met de repo-naam als mapnaam. Dat is precies
 * waar ProjectService.Scan() naar kijkt, dus de clone verschijnt daarna als
 * gewoon project.
 * 
 * De run is sequentieel en gaat door na een fout: elke repo levert een eigen
 * OrgCloneOutcome op. Een bestaande doelmap wordt overgeslagen, nooit
 * overschreven.
 */
export function Clone(names: string[]): $CancellablePromise<domain$0.OrgCloneResult> {
    return $Call.ByID(2652117025, names).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Last laadt het laatst opgeslagen resultaat en voert de matching tegen de
 * actuele lokale projecten opnieuw uit (dat is gratis en lokaal, dus "lokaal
 * aanwezig" klopt ook zonder nieuwe netwerksync).
 */
export function Last(): $CancellablePromise<domain$0.OrgSyncResult> {
    return $Call.ByID(1002902588).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Org bepaalt de GitHub-organisatie op basis van de remotes van de lokale
 * checkouts. Vooral bedoeld voor tests en losstaand gebruik; Sync roept
 * dezelfde logica intern aan.
 */
export function Org(): $CancellablePromise<string> {
    return $Call.ByID(803398690);
}

/**
 * SetApp injects the Wails app reference (called after app creation).
 */
export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(4158726391, app);
}

/**
 * Sync haalt de volledige repolijst van de organisatie op, classificeert elke
 * niet-archived repo waarvan de PushedAt is gewijzigd (of altijd bij force),
 * en matcht het resultaat tegen de lokale checkouts.
 */
export function Sync(force: boolean): $CancellablePromise<domain$0.OrgSyncResult> {
    return $Call.ByID(3730605999, force).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = domain$0.OrgCloneResult.createFrom;
const $$createType1 = domain$0.OrgSyncResult.createFrom;
