// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PluginService compares the paid-plugin repo manifest against the plugins
 * installed on a Kinsta environment.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../domain/models.js";

/**
 * Diff compares the plugins installed on a Kinsta environment against the
 * paid-plugin manifest.
 * @param {string} envID
 * @returns {$CancellablePromise<domain$0.PluginDiff[]>}
 */
export function Diff(envID) {
    return $Call.ByID(525779441, envID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * IsConfigured reports whether the paid-plugin repo is set up.
 * @returns {$CancellablePromise<boolean>}
 */
export function IsConfigured() {
    return $Call.ByID(2591742414);
}

/**
 * ListPaidPlugins returns the manifest, cached after the first fetch.
 * @returns {$CancellablePromise<domain$0.PaidPlugin[]>}
 */
export function ListPaidPlugins() {
    return $Call.ByID(508849748).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * RefreshIndex discards the cache and re-fetches the manifest.
 * @returns {$CancellablePromise<void>}
 */
export function RefreshIndex() {
    return $Call.ByID(345095479);
}

/**
 * UpdateViaSSH downloads the paid plugin's zip from the private repo, uploads it
 * to the target host, and installs it via wp-cli (--force overwrites the current
 * version). The uploaded temp file is removed afterwards. Returns wp-cli stdout.
 * @param {domain$0.SSHTarget} target
 * @param {string} slug
 * @returns {$CancellablePromise<string>}
 */
export function UpdateViaSSH(target, slug) {
    return $Call.ByID(4201661661, target, slug);
}

// Private type creation functions
const $$createType0 = domain$0.PluginDiff.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = domain$0.PaidPlugin.createFrom;
const $$createType3 = $Create.Array($$createType2);
