// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../domain/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../wailsapp/wails/v3/pkg/application/models.js";

/**
 * AddRoot opens a native folder picker, adds the chosen folder, persists it, and returns updated roots.
 */
export function AddRoot(): $CancellablePromise<string[]> {
    return $Call.ByID(510438811).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * BatchStatus returns a lightweight status summary for all projects (sidebar use).
 */
export function BatchStatus(): $CancellablePromise<domain$0.ProjectStatusSummary[]> {
    return $Call.ByID(2706369086).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetRoots returns the currently configured project roots.
 */
export function GetRoots(): $CancellablePromise<string[]> {
    return $Call.ByID(4258866777).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * List returns the last scanned project list without re-scanning.
 */
export function List(): $CancellablePromise<domain$0.Project[]> {
    return $Call.ByID(1454748020).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * RefreshOne updates git status for a single project by ID.
 */
export function RefreshOne(id: string): $CancellablePromise<domain$0.Project> {
    return $Call.ByID(4057779285, id).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * RemoveRoot removes a folder from the configured roots and persists.
 */
export function RemoveRoot(path: string): $CancellablePromise<string[]> {
    return $Call.ByID(2690822668, path).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Scan discovers all projects under configured roots and refreshes git status.
 */
export function Scan(): $CancellablePromise<domain$0.Project[]> {
    return $Call.ByID(356497485).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * SetApp injects the Wails app reference (called after app creation).
 */
export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(1218819383, app);
}

/**
 * UpdateProjectConfig replaces the Config of a project in-memory (used after saving .rdm.yml).
 */
export function UpdateProjectConfig(id: string, cfg: domain$0.ProjectConfig): $CancellablePromise<void> {
    return $Call.ByID(4010355408, id, cfg);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = domain$0.ProjectStatusSummary.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = domain$0.Project.createFrom;
const $$createType4 = $Create.Array($$createType3);
