// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../domain/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../wailsapp/wails/v3/pkg/application/models.js";

/**
 * AddRoot opens a native folder picker, adds the chosen folder, persists it, and returns updated roots.
 * @returns {$CancellablePromise<string[]>}
 */
export function AddRoot() {
    return $Call.ByID(510438811).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * BatchStatus returns a lightweight status summary for all projects (sidebar use).
 * @returns {$CancellablePromise<domain$0.ProjectStatusSummary[]>}
 */
export function BatchStatus() {
    return $Call.ByID(2706369086).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * Get returns a project by ID from the last scan.
 * @param {string} id
 * @returns {$CancellablePromise<[domain$0.Project, boolean]>}
 */
export function Get(id) {
    return $Call.ByID(2540875416, id).then(/** @type {($result: any) => any} */(($result) => {
        $result[0] = $$createType3($result[0]);
        return $result;
    }));
}

/**
 * GetRoots returns the currently configured project roots.
 * @returns {$CancellablePromise<string[]>}
 */
export function GetRoots() {
    return $Call.ByID(4258866777).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * List returns the last scanned project list without re-scanning.
 * @returns {$CancellablePromise<domain$0.Project[]>}
 */
export function List() {
    return $Call.ByID(1454748020).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * RefreshOne updates git status for a single project by ID.
 * @param {string} id
 * @returns {$CancellablePromise<domain$0.Project>}
 */
export function RefreshOne(id) {
    return $Call.ByID(4057779285, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * RemoveRoot removes a folder from the configured roots and persists.
 * @param {string} path
 * @returns {$CancellablePromise<string[]>}
 */
export function RemoveRoot(path) {
    return $Call.ByID(2690822668, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Scan discovers all projects under configured roots and refreshes git status.
 * @returns {$CancellablePromise<domain$0.Project[]>}
 */
export function Scan() {
    return $Call.ByID(356497485).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * SetApp injects the Wails app reference (called after app creation).
 * @param {application$0.App | null} app
 * @returns {$CancellablePromise<void>}
 */
export function SetApp(app) {
    return $Call.ByID(1218819383, app);
}

/**
 * UpdateProjectConfig replaces the Config of a project in-memory (used after saving .rdm.yml).
 * @param {string} id
 * @param {domain$0.ProjectConfig} cfg
 * @returns {$CancellablePromise<void>}
 */
export function UpdateProjectConfig(id, cfg) {
    return $Call.ByID(4010355408, id, cfg);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = domain$0.ProjectStatusSummary.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = domain$0.Project.createFrom;
const $$createType4 = $Create.Array($$createType3);
