// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ReportService builds, persists and exports the per-project client report
 * ("Servicecontract rapportage", Bitfactory house style).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../domain/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../wailsapp/wails/v3/pkg/application/models.js";

/**
 * ExportPDF renders the stored report for projectID+period to HTML, asks the
 * user (via native save dialog) where to save it, then renders it to PDF via
 * the Playwright sidecar. Returns "" (no error) if the user cancels.
 * @param {string} projectID
 * @param {string} period
 * @returns {$CancellablePromise<string>}
 */
export function ExportPDF(projectID, period) {
    return $Call.ByID(3397979065, projectID, period);
}

/**
 * GetReport returns the stored draft for projectID+period, or a fresh
 * skeleton (default rows, prefilled client/website name) if none exists yet.
 * @param {string} projectID
 * @param {string} period
 * @returns {$CancellablePromise<domain$0.Report>}
 */
export function GetReport(projectID, period) {
    return $Call.ByID(2948716555, projectID, period).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * ListReports returns the stored report drafts for a project, newest first.
 * @param {string} projectID
 * @returns {$CancellablePromise<domain$0.Report[]>}
 */
export function ListReports(projectID) {
    return $Call.ByID(3091130682, projectID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * Prefill starts from the stored (or skeleton) draft and fills in fields from
 * live Kinsta + security-scan data. Each source is best-effort: an error from
 * Kinsta or the security scan is skipped (non-fatal) so the rest of the
 * prefill still runs. Does NOT save the result.
 * @param {string} projectID
 * @param {string} period
 * @returns {$CancellablePromise<domain$0.Report>}
 */
export function Prefill(projectID, period) {
    return $Call.ByID(3533979421, projectID, period).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * SaveReport persists r, stamping UpdatedAt.
 * @param {domain$0.Report} r
 * @returns {$CancellablePromise<void>}
 */
export function SaveReport(r) {
    return $Call.ByID(1838992932, r);
}

/**
 * SetApp injects the Wails app reference (called after app creation), needed
 * for the native save-file dialog in ExportPDF.
 * @param {application$0.App | null} app
 * @returns {$CancellablePromise<void>}
 */
export function SetApp(app) {
    return $Call.ByID(963781032, app);
}

// Private type creation functions
const $$createType0 = domain$0.Report.createFrom;
const $$createType1 = $Create.Array($$createType0);
