// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GrepAll searches all git-tracked files across all repos for the given query.
 * @param {string} query
 * @returns {$CancellablePromise<$models.SearchHit[]>}
 */
export function GrepAll(query) {
    return $Call.ByID(2149079796, query).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.SearchHit.createFrom;
const $$createType1 = $Create.Array($$createType0);
