// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SecurityService fetches security-scan resultaten (composer + npm audit) die de
 * wekelijkse GitHub Actions workflow per project-repo als artifact uploadt.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetScanResults haalt het nieuwste security-audit artifact op voor het project.
 * Geeft een foutmelding als het project geen GitHub-remote heeft of als er nog
 * geen scan-artifact bestaat.
 */
export function GetScanResults(projectID: string): $CancellablePromise<$models.SecurityScanResult | null> {
    return $Call.ByID(3101183978, projectID).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.SecurityScanResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
