// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SecurityService fetches security-scan resultaten (composer + npm audit) die de
 * wekelijkse GitHub Actions workflow per project-repo als artifact uploadt.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DispatchWorkflow start handmatig een workflow_dispatch-run van workflowID op
 * de default branch van het project-repo.
 * @param {string} projectID
 * @param {number} workflowID
 * @returns {$CancellablePromise<void>}
 */
export function DispatchWorkflow(projectID, workflowID) {
    return $Call.ByID(794705320, projectID, workflowID);
}

/**
 * GetScanResults haalt het nieuwste security-audit artifact op voor het project.
 * Geeft een foutmelding als het project geen GitHub-remote heeft of als er nog
 * geen scan-artifact bestaat.
 * @param {string} projectID
 * @returns {$CancellablePromise<$models.SecurityScanResult | null>}
 */
export function GetScanResults(projectID) {
    return $Call.ByID(3101183978, projectID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * ListWorkflows haalt de actieve GitHub Actions workflows van het project-repo
 * op, elk met de status van de meest recente run (leeg als er nog geen run is).
 * @param {string} projectID
 * @returns {$CancellablePromise<$models.ProjectWorkflow[]>}
 */
export function ListWorkflows(projectID) {
    return $Call.ByID(785615671, projectID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.SecurityScanResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.ProjectWorkflow.createFrom;
const $$createType3 = $Create.Array($$createType2);
