// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Get returns the current settings.
 */
export function Get(): $CancellablePromise<$models.AppSettings> {
    return $Call.ByID(1251098340).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Save persists updated settings to ~/.config/rdm/config.yml.
 */
export function Save(settings: $models.AppSettings): $CancellablePromise<void> {
    return $Call.ByID(859849557, settings);
}

// Private type creation functions
const $$createType0 = $models.AppSettings.createFrom;
