// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Get returns the current settings.
 * @returns {$CancellablePromise<$models.AppSettings>}
 */
export function Get() {
    return $Call.ByID(1251098340).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Save persists updated settings to ~/.config/rdm/config.yml.
 * @param {$models.AppSettings} settings
 * @returns {$CancellablePromise<void>}
 */
export function Save(settings) {
    return $Call.ByID(859849557, settings);
}

// Private type creation functions
const $$createType0 = $models.AppSettings.createFrom;
