// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SSHService manages interactive SSH terminal sessions and streams their output
 * to the frontend via Wails events ("ssh:<id>:data" and "ssh:<id>:exit").
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../domain/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../wailsapp/wails/v3/pkg/application/models.js";

/**
 * Close terminates the session. Unknown IDs are a no-op.
 */
export function Close(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(482098145, sessionID);
}

/**
 * OpenSession starts an interactive shell and returns its session ID. Terminal
 * output arrives as base64 strings on the "ssh:<id>:data" event; "ssh:<id>:exit"
 * fires when the session ends.
 */
export function OpenSession(target: domain$0.SSHTarget, cols: number, rows: number): $CancellablePromise<string> {
    return $Call.ByID(1429264657, target, cols, rows);
}

/**
 * Resize updates the remote PTY size.
 */
export function Resize(sessionID: string, cols: number, rows: number): $CancellablePromise<void> {
    return $Call.ByID(4284466515, sessionID, cols, rows);
}

/**
 * SetApp injects the Wails app reference (called after app creation).
 */
export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(2981691064, app);
}

/**
 * Write sends keyboard input to the session.
 */
export function Write(sessionID: string, data: string): $CancellablePromise<void> {
    return $Call.ByID(2911096206, sessionID, data);
}
