// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TestService orchestrates AI visual test runs and flow management.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../domain/models.js";

/**
 * AuthorFlow turns a natural-language description into flow steps via Claude.
 * @param {string} projectID
 * @param {string} description
 * @returns {$CancellablePromise<domain$0.Step[]>}
 */
export function AuthorFlow(projectID, description) {
    return $Call.ByID(446972150, projectID, description).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetRun returns a single stored run.
 * @param {string} projectID
 * @param {string} runID
 * @returns {$CancellablePromise<domain$0.TestRun>}
 */
export function GetRun(projectID, runID) {
    return $Call.ByID(2251477140, projectID, runID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * ListFlows returns the committed flows for a project.
 * @param {string} projectID
 * @returns {$CancellablePromise<domain$0.Flow[]>}
 */
export function ListFlows(projectID) {
    return $Call.ByID(3116154314, projectID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * ListRuns returns the run history for a project, newest first.
 * @param {string} projectID
 * @returns {$CancellablePromise<domain$0.TestRun[]>}
 */
export function ListRuns(projectID) {
    return $Call.ByID(489365043, projectID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * Run executes a flow on two environments, self-heals failed steps once,
 * compares screenshots, computes console/status regressions, saves and returns
 * the run. baselineEnv is the release side. override, when non-empty, forces the
 * model tier for every AI call in the run ("" = automatic routing).
 * @param {string} projectID
 * @param {string} flowName
 * @param {domain$0.EnvKey} baselineEnv
 * @param {domain$0.EnvKey} updateEnv
 * @param {domain$0.ModelTier} override
 * @returns {$CancellablePromise<domain$0.TestRun>}
 */
export function Run(projectID, flowName, baselineEnv, updateEnv, override) {
    return $Call.ByID(3168086190, projectID, flowName, baselineEnv, updateEnv, override).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * SaveFlows validates and writes the flows for a project.
 * @param {string} projectID
 * @param {domain$0.Flow[]} flows
 * @returns {$CancellablePromise<void>}
 */
export function SaveFlows(projectID, flows) {
    return $Call.ByID(2629359469, projectID, flows);
}

/**
 * Screenshot returns a run screenshot as a data: URL for the webview. The path
 * must live inside the run-history directory.
 * @param {string} path
 * @returns {$CancellablePromise<string>}
 */
export function Screenshot(path) {
    return $Call.ByID(4281490373, path);
}

// Private type creation functions
const $$createType0 = domain$0.Step.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = domain$0.TestRun.createFrom;
const $$createType3 = domain$0.Flow.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $Create.Array($$createType2);
