// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../domain/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function LastFetched(): $CancellablePromise<$models.FeedMeta> {
    return $Call.ByID(1809317729).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * List returns the cached, parsed feed.
 */
export function List(): $CancellablePromise<domain$0.Vulnerability[]> {
    return $Call.ByID(1983209536).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * MatchProjects cross-references installed plugins against the cached feed.
 */
export function MatchProjects(): $CancellablePromise<$models.ProjectVulnReport[]> {
    return $Call.ByID(2090003843).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * Refresh downloads the feed, caches it, and records metadata.
 */
export function Refresh(): $CancellablePromise<$models.FeedMeta> {
    return $Call.ByID(401611139).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $models.FeedMeta.createFrom;
const $$createType1 = domain$0.Vulnerability.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $models.ProjectVulnReport.createFrom;
const $$createType4 = $Create.Array($$createType3);
